# serviceEndpoints:
#   - name: "yb-master-ui"
#     type: ClusterIP
#     app: "yb-master"
#     ports:
#       http-ui: "7000"
#
#   - name: "yb-tserver-service"
#     type: ClusterIP
#     app: "yb-tserver"
#     ports:
#       tcp-yql-port: "9042"
#       tcp-yedis-port: "6379"
#       tcp-ysql-port: "5433"

storage:
  master:
    count: 2
    size: 2Gi
    storageClass: local-path
  tserver:
    count: 2
    size: 2Gi
    storageClass: local-path


resource:
  master:
    requests:
      cpu: 0.25
      memory: 512Mi
    limits:
      cpu: 2
      memory: 2Gi
  tserver:
    requests:
      cpu: 0.25
      memory: 512Mi
    limits:
      cpu: 2
      memory: 2Gi


enableLoadBalancer: false

authCredentials:
  ysql:
    user: "direktiv"
    password: "helloworld"
    database: "direktiv"

tls:
  enabled: true
