apiVersion: v1
kind: Secret
metadata:
  name: {{ include "direktiv.fullname" . }}-secrets-functions
  namespace: {{ .Values.functions.namespace }}
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.functions.db }}
  db: {{ .Values.functions.db | b64enc | quote }}
  {{- else }}
  db: {{ printf "host=%s-support.%s port=5432 user=direktiv dbname=direktiv password=direktivdirektiv sslmode=disable" ( include "direktiv.fullname" . ) .Release.Namespace  | b64enc | quote }}
  {{- end }}
