// Code generated by entc, DO NOT EDIT.

package server

import (
	"time"
)

const (
	// Label holds the string label denoting the server type in the database.
	Label = "server"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldExtIP holds the string denoting the extip field in the database.
	FieldExtIP = "ext_ip"
	// FieldNatsPort holds the string denoting the natsport field in the database.
	FieldNatsPort = "nats_port"
	// FieldMemberPort holds the string denoting the memberport field in the database.
	FieldMemberPort = "member_port"
	// FieldAdded holds the string denoting the added field in the database.
	FieldAdded = "added"

	// Table holds the table name of the server in the database.
	Table = "servers"
)

// Columns holds all SQL columns for server fields.
var Columns = []string{
	FieldID,
	FieldIP,
	FieldExtIP,
	FieldNatsPort,
	FieldMemberPort,
	FieldAdded,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IPValidator is a validator for the "ip" field. It is called by the builders before save.
	IPValidator func(string) error
	// ExtIPValidator is a validator for the "extIP" field. It is called by the builders before save.
	ExtIPValidator func(string) error
	// DefaultAdded holds the default value on creation for the "added" field.
	DefaultAdded func() time.Time
)
