apiVersion: batch/v1
kind: Job
metadata:
  name: runitfast
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name: runitfast
    spec:
      volumes:
      - name: workdir
        emptyDir: {}
      # initContainers:
      # - name: init-data
      #   image: localhost:5000/init-pod
      #   imagePullPolicy: Always
      #   volumeMounts:
      #   - name: workdir
      #     mountPath: /direktiv-data
      #   ports:
      #   - containerPort: 8890
      #   env:
      #   - name: DIREKTIV_LIFECYCLE
      #     value: "init"
      containers:
      - name: runthing
        image: localhost:5000/init-pod
        # imagePullPolicy: Always
        ports:
        - containerPort: 8888
        env:
        - name: DIREKTIV_LIFECYCLE
          value: "run"
        volumeMounts:
        - name: workdir
          mountPath: /direktiv-data
      - name: pi
        image: perl
        command: ["perl", "-wle", "open OUTPUT, '>', '/direktiv-data/out.log'; select OUTPUT; $| = 1; print 'JENSGERKE'; open(FH, '>', '/direktiv-data/output.json'); print FH '{ \"data\": \"out\" }' ; open FILE, '>/direktiv-data/done';"]
        volumeMounts:
        - name: workdir
          mountPath: /direktiv-data
      restartPolicy: Never
