# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
openapi.yaml:
  struct:
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1events~1history/get/responses/200/content/application~1json/schema/properties/data/items/properties/serialID/type
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1events~1listeners/get/responses/200/content/application~1json/schema/properties/data/items/properties/id/required
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1events~1listeners/get/responses/200/content/application~1json/schema/properties/data/items/properties/createdAt/required
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1events~1listeners/get/responses/200/content/application~1json/schema/properties/data/items/properties/updatedAt/required
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1events~1listeners/get/responses/200/content/application~1json/schema/properties/data/items/properties/namespace/required
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1events~1listeners/get/responses/200/content/application~1json/schema/properties/data/items/properties/namespaceID/required
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1events~1listeners/get/responses/200/content/application~1json/schema/properties/data/items/properties/triggerType/required
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1events~1listeners~1{listenerID}/get/responses/200/content/application~1json/schema/properties/data/properties/id/required
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1events~1listeners~1{listenerID}/get/responses/200/content/application~1json/schema/properties/data/properties/createdAt/required
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1events~1listeners~1{listenerID}/get/responses/200/content/application~1json/schema/properties/data/properties/updatedAt/required
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1events~1listeners~1{listenerID}/get/responses/200/content/application~1json/schema/properties/data/properties/namespaceID/required
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1events~1listeners~1{listenerID}/get/responses/200/content/application~1json/schema/properties/data/properties/namespace/required
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1events~1listeners~1{listenerID}/get/responses/200/content/application~1json/schema/properties/data/properties/triggerType/required
    - >-
      #/components/schemas/route/properties/spec/properties/x-direktiv-config/properties/plugins/properties/outbound/items/properties/configuration/type
    - >-
      #/components/schemas/route/properties/spec/properties/x-direktiv-config/properties/plugins/properties/inbound/items/properties/configuration/type
    - >-
      #/components/schemas/route/properties/spec/properties/x-direktiv-config/properties/plugins/properties/auth/items/properties/configuration/type
    - >-
      #/components/schemas/route/properties/spec/properties/x-direktiv-config/properties/plugins/properties/target/properties/configuration/type
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1metrics~1instance/get/responses/200/content/application~1json/schema/properties/data/properties/complete/type
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1metrics~1instance/get/responses/200/content/application~1json/schema/properties/data/properties/failed/type
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1metrics~1instance/get/responses/200/content/application~1json/schema/properties/data/properties/cancelled/type
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1metrics~1instance/get/responses/200/content/application~1json/schema/properties/data/properties/crashed/type
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1metrics~1instance/get/responses/200/content/application~1json/schema/properties/data/properties/pending/type
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1metrics~1instance/get/responses/200/content/application~1json/schema/properties/data/properties/total/type
    - >-
      #/paths/~1api~1v2~1namespaces/get/responses/200/content/application~1json/schema/properties/data/items/properties/mirror/properties/publicKey/type
    - >-
      #/paths/~1api~1v2~1namespaces/post/requestBody/content/application~1json/schema/properties/mirror/properties/authToken/type
    - >-
      #/paths/~1api~1v2~1namespaces/post/requestBody/content/application~1json/schema/properties/mirror/properties/publicKey/type
    - >-
      #/paths/~1api~1v2~1namespaces/post/requestBody/content/application~1json/schema/properties/mirror/properties/privateKey/type
    - >-
      #/paths/~1api~1v2~1namespaces/post/requestBody/content/application~1json/schema/properties/mirror/properties/privateKeyPassphrase/type
    - >-

      #/paths/~1api~1v2~1namespaces/post/responses/200/content/application~1json/schema/properties/data/properties/mirror/properties/publicKey/type
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}/get/responses/200/content/application~1json/schema/properties/data/properties/mirror/properties/publicKey/type
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}/patch/requestBody/content/application~1json/schema/properties/mirror/properties/authToken/type
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}/patch/requestBody/content/application~1json/schema/properties/mirror/properties/publicKey/type
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}/patch/requestBody/content/application~1json/schema/properties/mirror/properties/privateKey/type
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}/patch/requestBody/content/application~1json/schema/properties/mirror/properties/privateKeyPassphrase/type
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}/patch/responses/200/content/application~1json/schema/properties/data/properties/mirror/properties/publicKey/type
    - >-
      #/paths/~1api~1v2~1namespaces~1{namespace}~1services/get/responses/200/content/application~1json/schema/properties/data/items/properties/error/type/1
