storage:
  master:
    count: 2
    storageClass: local-path
  tserver:
    count: 2
    storageClass: local-path

enableLoadBalancer: false

authCredentials:
  ysql:
    user: "direktiv"
    password: "direktiv"
    database: "direktiv"

tls:
  enabled: true
