apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: direktiv
  namespace: postgres
spec:
  postgresVersion: 14
  instances:
    - name: "direktiv"
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
  proxy:
    pgBouncer:
      replicas: 2
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "postgres-operator.crunchydata.com/cluster"
                  operator: In
                  values:
                  - direktiv
            topologyKey: "kubernetes.io/hostname"
  backups:
    pgbackrest:
      global:
        # Keep 4 Backups
        repo1-retention-full: "4"
        repo1-retention-full-type: count
      repos:
      - name: repo1
        schedules:
          # Run every Sunday
          full: "0 1 * * 0"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: "4Gi"