  apiVersion: postgres-operator.crunchydata.com/v1beta1
  kind: PostgresCluster
  metadata:
    name: direktiv
    namespace: postgres
  spec:
    postgresVersion: 14
    instances:
      - name: "instance1"
        replicas: 1
        dataVolumeClaimSpec:
          accessModes:
          - "ReadWriteOnce"
          resources:
            requests:
              storage: "1Gi"
    backups:
      pgbackrest:
        configuration:
        - secret:
            name: direktiv-pgbackrest-secret
        global:
          repo1-retention-full: "4"
          repo1-retention-full-type: count
        repos:
        - name: repo1
          s3:
            bucket: my-bucket
            endpoint: s3.eu-central-1.amazonaws.com:443
            region: eu-central-1
          schedules:
            full: "0 1 * * 0"