version: "2"
checks:
  return-statements:
    enabled: true
    config:
      threshold: 6
  similar-code:
    enabled: true
    config:
      threshold: 120
exclude_patterns:
- "ent/"
- "pkg/secrets/ent/"
- "pkg/metrics/ent"
- "pkg/functions/ent"
- "pkg/flow/ent"
- "pkg/api/client"
- "pkg/api/models"
- "cmd/flow/tests-api.go"
- "cmd/flow/test-api.go"
- "**/*.pb.go"
- "ui/"
