run:
  timeout: 10m
  go: 1.21.0
  issues-exit-code: 1
  tests: false
  skip-files: [ ".pb.go" ]

linters-settings:
  tagliatelle:
    # Check the struck tag name case.
    case:
      # Use the struct field name to check the name of the struct tag.
      # Default: false
      use-field-name: true
      rules:
        json: snake
        yaml: snake

linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - wsl
    - lll
    - varnamelen
    - wrapcheck
    - nolintlint # must fix before release.
    - ireturn
    - funlen
    - gochecknoglobals
    - cyclop
    - godox # must fix before release.

    - exhaustivestruct
    - structcheck
    - ifshort
    - maligned
    - interfacer
    - nosnakecase
    - golint
    - deadcode
    - varcheck
    - scopelint

issues:
  exclude-rules:
    - path: '(pkg|cmd)\/(version|dlog|model|sidecar|secrets|exec|util|jqer|functions|flow|api|metrics)\/.*'
      linters:
        - paralleltest
        - forbidigo
        - protogetter
        - perfsprint
        - nlreturn
        - nonamedreturns
        - stylecheck
        - tagliatelle
        - wastedassign
        - gomnd
        - testpackage
        - asasalint
        - predeclared
        - musttag
        - maintidx
        - interfacebloat
        - forcetypeassert
        - exhaustive
        - contextcheck
        - unparam
        - revive
        - promlinter
        - prealloc
        - nestif
        - makezero
        - dogsled
        - dupl
        - gochecknoinits
        - gocognit
        - gosec
        - gocritic
        - rowserrcheck
        - nakedret
        - unused
        - gocyclo

    - text: "do not define dynamic errors, use wrapped static errors instead:"
      linters:
        - goerr113
    - text: "ifElseChain: rewrite if-else to switch statement"
      linters:
        - gocritic