version: "2"
run:
  issues-exit-code: 1
  tests: false

linters:
  default: all

  disable:
    - canonicalheader
    - cyclop
    - depguard
    - err113 # TODO: This ensures no dynamic errors.
    - exhaustruct
    - funlen
    - gochecknoglobals
    - godox
    - ireturn
    - lll
    - mnd
    - musttag
    - prealloc
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
    - funcorder
    - wsl_v5
    - noinlineerr

  settings:
    nlreturn:
      block-size: 2
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
        use-field-name: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
        text: 'do not define dynamic errors, use wrapped static errors instead:'
      - linters:
          - gocritic
        text: 'ifElseChain: rewrite if-else to switch statement'
      - linters:
          - errcheck
        text: Rollback` is not checked
      - linters:
          - errchkjson
        text: encoding/json.Encoder
      - linters:
          - errchkjson
        text: encoding/json.Marshal
      - linters:
          - staticcheck
        text: 'SA1029: should not use built-in type string as key for value'
      - linters:
          - revive
        text: 'unused-parameter:'
      - linters:
          - revive
        text: 'empty-block:'
      - linters:
          - revive
        text: 'var-naming:'
      - linters:
          - revive
        text: 'context-as-argument:'
      - linters:
          - revive
        text: 'context-keys-type: should not use basic type'
      - linters:
          - perfsprint
        text: fmt.Errorf can be replaced
      - linters:
          - perfsprint
        text: fmt.Sprintf can be replaced
      - linters:
          - init
        text: don't use `init` function
      - linters:
          - goconst
        text: string `true`
      - linters:
          - goconst
        text: string `false`
      - linters:
          - gochecknoinits
        path: internal/gateway/plugins/.*

      - path: "cmd/cli/cli.go"
        linters: [forbidigo]

      - path: "cmd/cli/filesystem_helper.go"
        linters: [forbidigo, gosec]

      - path: "cmd/cli/uploader_helper.go"
        linters: [gosec, nlreturn, forbidigo]

      - path: "internal/api/filesystem.go"
        linters: [gocognit]

      - path: "internal/api/api.go"
        linters: [forcetypeassert]

      - path: "internal/api/namespaces.go"
        linters: [forcetypeassert]

      - path: "internal/api/filter/filter.go"
        linters: [nestif, nonamedreturns]

      - path: "internal/api/jx.go"
        linters: [contextcheck]

      - path: "internal/api/middlewares.go"
        linters: [contextcheck]

      - path: "internal/api/secrets.go"
        linters: [errcheck]

      - path: "internal/api/services.go"
        linters: [forcetypeassert]

      - path: "internal/cluster/cache/cache.go"
        linters: [revive]

      - path: "internal/cluster/cache/memcache/memcache.go"
        linters: [exhaustive]

      - path: "internal/cluster/certs/certs.go"
        linters: [gosec]

      - path: "internal/cluster/certs/updater.go"
        linters: [gosec]

      - path: "internal/cluster/pubsub/nats/pubsub.go"
        linters: [revive]

      - path: "internal/cmdserver/pkg/server/commands.go"
        linters: [contextcheck, errcheck, modernize, nlreturn]

      - path: "internal/cmdserver/pkg/server/server.go"
        linters: [gocritic, gosec]

      - path: "internal/compiler/ast.go"
        linters: [gocognit, goconst, nestif, wastedassign, gocyclo, maintidx]

      - path: "internal/compiler/transpiler.go"
        linters: [forcetypeassert]

      - path: "internal/core/registry.go"
        linters: [modernize]

      - path: "internal/datastore/datasql/runtime_variables.go"
        linters: [goconst]

      - path: "internal/datastore/datasql/mirror.go"
        linters: [unqueryvet]

      - path: "internal/datastore/eventsstore.go"
        linters: [godoclint]

      - path: "internal/datastore/mirrors.go"
        linters: [goconst, godoclint, interfacebloat]

      - path: "internal/datastore/runtime_variables.go"
        linters: [interfacebloat]

      - path: "internal/datastore/traces.go"
        linters: [modernize]

      - path: "internal/engine/databus/databus.go"
        linters: [unparam]

      - path: "internal/engine/runtime/commands_http.go"
        linters: [errcheck, forcetypeassert, gosec, noctx, revive]

      - path: "internal/engine/runtime/runtime.go"
        linters: [contextcheck, errcheck, forbidigo, revive]

      - path: "internal/engine/runtime/runtime_action.go"
        linters: [errcheck]

      - path: "internal/engine/runtime/tracing.go"
        linters: [containedctx, spancheck]

      - path: "internal/engine/worker.go"
        linters: [unparam]

      - path: "internal/gateway/gateway.go"
        linters: [contextcheck]

      - path: "internal/gateway/plugins/inbound/js-inbound.go"
        linters: [errcheck, forcetypeassert]

      - path: "internal/gateway/plugins/outbound/js_outbound.go"
        linters: [forcetypeassert]

      - path: "internal/gateway/plugins/target/instant-response.go"
        linters: [errcheck]

      - path: "internal/gateway/router.go"
        linters: [gocognit, forcetypeassert]

      - path: "internal/jqer/jqer.go"
        linters: [errcheck, gocognit, gosec, makezero]

      - path: "internal/mirroring/mirror.go"
        linters: [contextcheck, gocognit]

      - path: "internal/mirroring/source.go"
        linters: [gosec]

      - path: "internal/nats/nats.go"
        linters: [godoclint]

      - path: "internal/sched/sched.go"
        linters: [unparam]

      - path: "internal/sched/ticker.go"
        linters: [forbidigo, gosec]

      - path: "internal/server/render.go"
        linters: [exhaustive, forbidigo, gocritic, gocognit]

      - path: "internal/server/server.go"
        linters: [errcheck, gocognit, ineffassign, revive, staticcheck, wastedassign, gocyclo, maintidx]

      - path: "internal/service/helper.go"
        linters: [gosec]

      - path: "internal/service/manager.go"
        linters: [unparam]

      - path: "internal/sidecar/external.go"
        linters: [gosec, spancheck]

      - path: "internal/sidecar/internal.go"
        linters: [gosec]

      - path: "internal/sidecar/sidecar.go"
        linters: [contextcheck, noctx, staticcheck, forcetypeassert]

      - path: "internal/telemetry/logs.go"
        linters: [forcetypeassert]

      - path: "pkg/filestore/filesql/filestore.go"
        linters: [unqueryvet]

      - path: "pkg/filestore/filesql/root_query.go"
        linters: [unqueryvet]

      - path: "pkg/lifecycle/circuit.go"
        linters: [containedctx]

      - path: "pkg/utils/regex.go"
        linters: [gochecknoinits, gocritic, gosec]

    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
