run:
  timeout: 10m
  go: 1.20.0
  issues-exit-code: 1
  tests: true
  skip-dirs: ["ent/"]
  skip-files: [".pb.go"]

linters:
  disable:
    - exhaustruct
    - wsl
    - prealloc
    - lll
    - varnamelen
    - paralleltest
    - wrapcheck
    - nolintlint
    - ireturn
    - funlen
    - musttag
    - gochecknoglobals
    - cyclop
    - godox # must fix


    # Workarround to fix issue https://github.com/golangci/golangci-lint/issues/3711
    # This workarround is mentioned here https://github.com/golangci/golangci-lint/issues/3086#issuecomment-1475232706
    # under "current list".
    # TODO: watch for new golangci-lint version to fix this issue.
    - bodyclose # must fix
    - contextcheck
    - nilerr
    - rowserrcheck
    - unparam
    - noctx
    - sqlclosecheck
    - tparallel
    - wastedassign


  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

issues:
  exclude-rules:
    - path: '(pkg|cmd)\/(version|dlog|model|sidecar|secrets|exec|util|jqer|functions|flow|api|flow-dbinit|metrics)\/.*'
      linters:
      - wrapcheck
      - varnamelen
      - exhaustivestruct
      - exhaustruct
      - golint
      - wsl
      - funlen
      - paralleltest
      - forbidigo
      - cyclop
      - nosnakecase
      - scopelint

      - nlreturn
      - nonamedreturns
      - stylecheck
      - tagliatelle
      - wastedassign
      - gomnd
      - testpackage
      - gochecknoglobals
      - bodyclose # must fix
      - asasalint
      - predeclared
      - musttag
      - maintidx
      - ireturn
      - interfacebloat
      - forcetypeassert
      - exhaustive
      - contextcheck
      - unparam
      - revive
      - promlinter
      - prealloc
      - nestif
      - makezero
      - dogsled
      - dupl
      - gochecknoinits
      - gocognit
      - godox
      - gosec
      - lll
      - gocritic
      - rowserrcheck
      - nakedret
      - unused

    - text: "do not define dynamic errors, use wrapped static errors instead:"
      linters:
      - goerr113
