version: "3.9"
services:
  postgres:
    image: postgres:15
    command: [
        "postgres",
        ## "-c", "log_statement=all",
        ## "-c", "log_destination=stderr",
      ]
    environment:
      POSTGRES_USER: myadmin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      POSTGRES_INITDB_ARGS: "-A password"
    ports:
      - "5432:5432"
    volumes: []

  flow:
    image: direktiv
    command: ["/bin/direktiv", "server"]
    environment:
      - DIREKTIV_API_PORT=8181
      - DIREKTIV_DEBUG=true

      - DIREKTIV_DB=host=postgres port=5432 user=myadmin dbname=mydb password=mypassword sslmode=disable
      - DIREKTIV_SECRET_KEY=01234567890123456789012345678912
      - DIREKTIV_DISABLE_SERVICES=false

      - DIREKTIV_KNATIVE_NAMESPACE=direktiv-services-direktiv
      - DIREKTIV_FUNCTIONS_TIMEOUT=7200
      - DIREKTIV_LOG_JSON=console

      # for external Kubernetes/Knative connectivity
      - KUBERNETES_HOST=192.168.122.44:6443
      - INGRESS_HOST=192.168.122.44
      - KUBERNETES_TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6InBnNE55Z1Y2QkNjdjBtRE84NlNSdjVGMjNWOXpVdWdzRnJIZVJ1cTh4SVUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkaXJla3Rpdi1zZXJ2aWNlcy1kaXJla3RpdiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkaXJla3Rpdi1rbmF0aXZlLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRpcmVrdGl2LWtuYXRpdmUtc2VydmljZS1hY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYjM4MWYzM2MtOWY2NC00YjE0LTk5ZTctMDU3Nzk2MGE0N2MyIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRpcmVrdGl2LXNlcnZpY2VzLWRpcmVrdGl2OmRpcmVrdGl2LWtuYXRpdmUtc2VydmljZS1hY2NvdW50In0.jIA_5eonea2tcUHcqs_GHrQmZT7PwEJaQSwNPP1-mcY773oTsEi_IiP_Rcv5Y0vy1y7h-CyJLcJt7JTmfVxV-egARgkajib93xpXTOELZCcccgWOe-OmoE_lvwBcwfb54xDgBbvm_75QkgENpmEn3cTTbmKWcV2eSbFpCcqBICRjl3WjjWEG_mm0l7OgpTVy4xjWf21oDho_R1Tj1IZ5ORsqn6ZDCxC0KratOWjZ1pbiwHHrmLwQHUrV2Dp7sP1DNlCQesOGnuCmBZRhM7EKclY6chcbChqxgACSqSEuT0Es502bnaUeJhfARO8G1LL1ekyGM8VThMD6kzE5xjni9Q
      - DIREKTIV_KNATIVE_SERVICE_ACCOUNT=direktiv-knative-service-account
      - DIREKTIV_KNATIVE_INGRESS_CLASS=contour.ingress.networking.knative.dev
      - DIREKTIV_FLOW_ENDPOINT=192.168.178.106
      - DIREKTIV_KNATIVE_SIDECAR=h8718/direktiv:latest
    ports:
      # api port
      - "8181:8181"
    depends_on:
      - postgres

  ui:
    image: direktiv-ui
    environment:
      - DIREKTIV_UI_PORT=8080
      - DIREKTIV_UI_BACKEND=http://flow:8181/api/
    ports:
      # api port
      - "8080:8080"
    depends_on:
      - flow

  e2e-api:
    image: node:lts-alpine3.18
    volumes:
      - ./tests:/tests
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - DIREKTIV_HOST=http://flow:8181
    command: npm --prefix /tests run jest -- ${JEST_PREFIX} --runInBand
    depends_on:
      - flow

  e2e-playwright:
    scale: 0
    image: node:18
    volumes:
      - ./ui:/ui
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - PLAYWRIGHT_USE_VITE=FALSE
      - PLAYWRIGHT_UI_BASE_URL=http://ui:8080
    command: >
      bash -c "cd ui
      && yarn
      && npx playwright install --with-deps chromium
      && yarn run e2e:headless-chromium-only"
    depends_on:
      - ui

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - flow
