FROM node:18 as build

ARG FULL_VERSION

RUN echo "building $FULL_VERSION"
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY public ./public
COPY src ./src
COPY package.json ./
COPY tsconfig.json ./
COPY yarn.lock ./

RUN yarn install --verbose --network-timeout 1000000
# If this causes problems on github actions: A potential fix is to change the builder image to `node:alpine`
RUN NODE_OPTIONS=--openssl-legacy-provider REACT_APP_VERSION=$FULL_VERSION yarn build