FROM nginx:bookworm

RUN ls -la
ADD dist /usr/share/nginx/html
COPY conf/prod/nginx.conf /etc/nginx/conf.d/default.conf

COPY conf/prod/entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]