apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
data:
  ingress.class: "contour.ingress.networking.knative.dev"  # Replace with your ingress class if different
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  192.168.122.44.nip.io: ""
