worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    server {
        listen 80;

        # Route /ns/* to the flow service
        location /ns/ {
            proxy_pass http://flow:8181/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Content-Length $http_content_length;
            proxy_pass_request_headers on;
        }


        # Default route for other paths
        location / {
            proxy_pass http://flow:8181/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Content-Length $http_content_length;
            proxy_pass_request_headers on;
        }
    }
}
