apiVersion: v1
kind: ServiceAccount
metadata:
  name: direktiv-knative-service-account
  namespace: direktiv-services-direktiv
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: direktiv-knative-clusterrole
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["serving.knative.dev"]
    resources: ["services"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: [""]
    resources: ["services", "endpoints", "events", "configmaps", "secrets"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: ["serving.knative.dev"]
    resources: ["services", "revisions"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: direktiv-knative-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: direktiv-knative-service-account
    namespace: direktiv-services-direktiv
roleRef:
  kind: ClusterRole
  name: direktiv-knative-clusterrole
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: direktiv-knative-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: direktiv-knative-service-account
    namespace: direktiv-services-direktiv
roleRef:
  kind: ClusterRole
  name: direktiv-knative-clusterrole
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: direktiv-services-direktiv
  name: direktiv-knative-role
rules:
  - apiGroups: ["serving.knative.dev"]
    resources: ["services"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "events", "configmaps", "secrets"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: direktiv-services-direktiv
  name: direktiv-knative-rolebinding
subjects:
  - kind: ServiceAccount
    name: direktiv-knative-service-account
    namespace: direktiv-services-direktiv
roleRef:
  kind: Role
  name: direktiv-knative-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
metadata:
  name: direktiv-knative-token
  namespace: direktiv-services-direktiv
  annotations:
    kubernetes.io/service-account.name: direktiv-knative-service-account
type: kubernetes.io/service-account-token
