version: '3'

includes:
  zarf:
    taskfile: ./zarf/taskfile.yaml
    dir: ./zarf
  cluster: 
    taskfile: taskfile-cluster.yaml
  version:  
    taskfile: taskfile-version.yaml


vars: 
  VERSION: '{{.VERSION | default "dev"}}'

tasks:  
  default:
    deps: [version:check] 
    cmds:
    - echo "{{.VERSION}}"
    silent: true