version: '3'

includes:
  zarf:
    taskfile: taskfile_zarf.yaml
  cluster: 
    taskfile: taskfile_cluster.yaml
  version:  
    taskfile: taskfile_version.yaml
  build:  
    taskfile: taskfile_build.yaml
  test:  
    taskfile: taskfile_test.yaml
    
tasks:  
  default:
    desc: Basic Kind cluster with Direktiv. Run with TELEMETRY=true to enable telemetry with grafana. 
    deps: [version:check] 
    cmds:
    - task: cluster:one-node
    - task: cluster:docker-proxy-create
    - task: cluster:database
    - task: build:build
    - task: cluster:install
    silent: true