apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "direktiv.fullname" . }}-config-flow
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}

data:
  flow-config.yaml: |

      functions-service: {{ include "direktiv.fullname" . }}-functions
      flow-service: {{ include "direktiv.fullname" . }}-flow


      # protocol used to access functions
      #functions-protocol: {{ .Values.flow.functionsProtocol }}
      #database: 'host=direktiv-support.default port=5432 user=direktiv password=direktivdirektiv dbname=postgres sslmode=disable'
      # database: 'host=192.168.1.60 port=5432 user=sisatech dbname=postgres password=sisatech sslmode=disable'

      # ingress -> bind_flow
      # flow -> bind_internal
      # TODO: yes I know this is confusing, maybe we should rename stuff
      #bind_flow: ':6666'
      #bind_internal: ':7777'
