apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-flow-hl
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    konghq.com/plugins: {{ include "direktiv.fullname" . }}-kong-plugin-grpc-gateway
    # konghq.com/plugins: {{ include "direktiv.fullname" . }}-kong-plugin-grpc-gateway,{{ include "direktiv.fullname" . }}-kong-plugin-grpc-stream
    konghq.com/protocol: "grpc"
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 6666
      name: ingress
      protocol: TCP
  selector:
    {{- include "direktiv.selectorLabels" . | nindent 4 }}
