apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-internal-hl
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 7777
      name: flow
      protocol: TCP
  selector:
    {{- include "direktiv.selectorLabels" . | nindent 4 }}
