apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "direktiv.fullname" . }}-config-flow
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}

data:
  flow-config.yaml: |

      functions-service: {{ include "direktiv.fullname" . }}-functions
      flow-service: {{ include "direktiv.fullname" . }}-flow

      prometheus-backend:
