apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "direktiv.fullname" . }}-config-flow
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}

data:
  flow-config.yaml: |
      functions-service: {{ include "direktiv.fullname" . }}-functions.{{ .Release.Namespace }}
      flow-service: {{ include "direktiv.fullname" . }}-flow.{{ .Release.Namespace }}
      {{- if .Values.thanos.enabled }}
      prometheus-backend: {{ include "direktiv.fullname" . }}-thanos-query-frontend.{{ .Release.Namespace }}
      {{- else }}
      prometheus-backend: {{ include "direktiv.fullname" . }}-prometheus-server
      {{- end }}
      redis-backend: {{ .Values.redis.address }}
      {{- if .Values.opentelemetry.address }}
      {{- if .Values.opentelemetry.enabled }}
      opentelemetry-backend: {{ .Values.opentelemetry.address }}
      {{- else }}
      opentelemetry-backend: none
      {{- end }}
      {{- else if .Values.opentelemetry.enabled }}
      opentelemetry-backend: host
      {{- else }}
      opentelemetry-backend: none
      {{- end }}
