apiVersion: v1
kind: Secret
metadata:
  name: {{ include "direktiv.fullname" . }}
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
type: Opaque
data:
   db: {{ printf "host=%s port=%d user=%s dbname=%s password=%s sslmode=%s" .Values.database.host ( .Values.database.port | int64 )  .Values.database.user .Values.database.name .Values.database.password .Values.database.sslmode | b64enc | quote }}
   key: {{ randAlphaNum 32 | b64enc | quote }}
