apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-vars
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    konghq.com/protocol: "http"
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  ports:
    - port: 9999
      name: vars
      protocol: TCP
  selector:
    {{- include "direktiv.selectorLabels" . | nindent 4 }}
