export const getCompanyListResponse = {
  status: "OK",
  code: 200,
  locale: "en_US",
  seed: null,
  total: 10,
  data: [
    {
      id: 1,
      name: "Wintheiser-Lebsack",
      email: "gibson.hope@watsica.org",
      vat: "4775194199",
      phone: "+12314635907",
      country: "Armenia",
      addresses: [
        {
          id: 1,
          street: "7632 Kling Lodge Apt. 642",
          streetName: "Calista Rapid",
          buildingNumber: "21831",
          city: "New Shanel",
          zipcode: "24889",
          country: "Qatar",
          country_code: "QA",
          latitude: 72.58785,
          longitude: -0.291611,
        },
      ],
      website: "http://morissette.org",
      image: "http://placeimg.com/640/480/people",
      contact: {
        id: 1,
        firstname: "Coleman",
        lastname: "Brown",
        email: "wbartoletti@gmail.com",
        phone: "+16196653162",
        birthday: "1999-06-25",
        gender: "other",
        address: {
          id: 1,
          street: "91093 Rahsaan Overpass",
          streetName: "Callie Vista",
          buildingNumber: "27081",
          city: "Lake Susieview",
          zipcode: "53493-6542",
          country: "Sweden",
          country_code: "SE",
          latitude: -59.323053,
          longitude: -37.153243,
        },
        website: "http://brown.com",
        image: "http://placeimg.com/640/480/people",
      },
    },
    {
      id: 2,
      name: "Tremblay, Rohan and Friesen",
      email: "verla53@gmail.com",
      vat: "8695906343",
      phone: "+14023954193",
      country: "Ecuador",
      addresses: [
        {
          id: 1,
          street: "70185 Bednar Ports Suite 528",
          streetName: "Kulas Junctions",
          buildingNumber: "5995",
          city: "Lake Maximotown",
          zipcode: "34169-9884",
          country: "Equatorial Guinea",
          country_code: "GQ",
          latitude: -88.674768,
          longitude: 88.334831,
        },
      ],
      website: "http://hackett.info",
      image: "http://placeimg.com/640/480/people",
      contact: {
        id: 1,
        firstname: "Hortense",
        lastname: "Sporer",
        email: "rbode@gmail.com",
        phone: "+13038946150",
        birthday: "2017-11-19",
        gender: "female",
        address: {
          id: 1,
          street: "5001 Polly Spurs",
          streetName: "Wisozk Ways",
          buildingNumber: "44951",
          city: "Zemlakport",
          zipcode: "47343-2815",
          country: "Cambodia",
          country_code: "KH",
          latitude: -26.720075,
          longitude: -178.660018,
        },
        website: "http://cruickshank.com",
        image: "http://placeimg.com/640/480/people",
      },
    },
    {
      id: 3,
      name: "Wiegand Inc",
      email: "chaya47@yahoo.com",
      vat: "67801272203",
      phone: "+19804465016",
      country: "Zambia",
      addresses: [
        {
          id: 1,
          street: "13726 Rasheed Ferry Suite 922",
          streetName: "Nader Station",
          buildingNumber: "67484",
          city: "Kshlerinville",
          zipcode: "83489-5335",
          country: "Argentina",
          country_code: "AR",
          latitude: 83.254938,
          longitude: -78.107556,
        },
      ],
      website: "http://koss.com",
      image: "http://placeimg.com/640/480/people",
      contact: {
        id: 1,
        firstname: "Clarabelle",
        lastname: "Maggio",
        email: "barrows.rosalinda@block.com",
        phone: "+12176030724",
        birthday: "1951-11-08",
        gender: "female",
        address: {
          id: 1,
          street: "95015 Gottlieb Squares",
          streetName: "Braden Shores",
          buildingNumber: "548",
          city: "Lake Kory",
          zipcode: "04928",
          country: "St. Kitts & Nevis",
          country_code: "KN",
          latitude: 47.737814,
          longitude: 22.561051,
        },
        website: "http://murphy.org",
        image: "http://placeimg.com/640/480/people",
      },
    },
    {
      id: 4,
      name: "Champlin Group",
      email: "hcummings@yahoo.com",
      vat: "53317840",
      phone: "+15514193603",
      country: "Papua New Guinea",
      addresses: [
        {
          id: 1,
          street: "4567 Kian Flats Suite 995",
          streetName: "Murphy Unions",
          buildingNumber: "1109",
          city: "New Skylachester",
          zipcode: "91514",
          country: "Montserrat",
          country_code: "MS",
          latitude: 59.033255,
          longitude: -83.397252,
        },
        {
          id: 1,
          street: "210 Madaline Village",
          streetName: "Taylor Circle",
          buildingNumber: "4535",
          city: "Mohrport",
          zipcode: "92063",
          country: "Mauritius",
          country_code: "MU",
          latitude: -17.196842,
          longitude: 141.077353,
        },
        {
          id: 1,
          street: "91672 Brain Mill Apt. 824",
          streetName: "Bogisich Highway",
          buildingNumber: "7974",
          city: "West Marjolaine",
          zipcode: "20524",
          country: "Faroe Islands",
          country_code: "FO",
          latitude: -32.556463,
          longitude: -144.023419,
        },
      ],
      website: "http://osinski.com",
      image: "http://placeimg.com/640/480/people",
      contact: {
        id: 1,
        firstname: "Carolyn",
        lastname: "Lehner",
        email: "green.tyson@hodkiewicz.info",
        phone: "+12623549320",
        birthday: "1989-11-24",
        gender: "other",
        address: {
          id: 1,
          street: "29516 Upton Fords",
          streetName: "Eva Springs",
          buildingNumber: "57886",
          city: "West Taureanport",
          zipcode: "19113",
          country: "Ecuador",
          country_code: "EC",
          latitude: -22.478525,
          longitude: 165.427143,
        },
        website: "http://williamson.com",
        image: "http://williamson.com",
      },
    },
    {
      id: 5,
      name: "McCullough, Ziemann and Hirthe",
      email: "keara.zemlak@hotmail.com",
      vat: "99990153014",
      phone: "+15205974471",
      country: "British Virgin Islands",
      addresses: [
        {
          id: 1,
          street: "69277 Borer Junction Suite 870",
          streetName: "Torey Circle",
          buildingNumber: "5299",
          city: "Swiftborough",
          zipcode: "15600",
          country: "Caribbean Netherlands",
          country_code: "BQ",
          latitude: -48.49306,
          longitude: 70.864273,
        },
        {
          id: 1,
          street: "22538 Upton Underpass Suite 943",
          streetName: "Kuhlman Drive",
          buildingNumber: "794",
          city: "South Zacheryberg",
          zipcode: "53996",
          country: "Malta",
          country_code: "MT",
          latitude: -33.681737,
          longitude: -65.90399,
        },
        {
          id: 1,
          street: "507 Rosenbaum Valley Apt. 984",
          streetName: "Efren Avenue",
          buildingNumber: "13593",
          city: "Herzogville",
          zipcode: "36055",
          country: "Brunei",
          country_code: "BN",
          latitude: -5.212567,
          longitude: -145.557953,
        },
      ],
      website: "http://schultz.com",
      image: "http://placeimg.com/640/480/people",
      contact: {
        id: 1,
        firstname: "Braden",
        lastname: "Cummings",
        email: "chickle@mitchell.com",
        phone: "+17204375030",
        birthday: "1962-01-05",
        gender: "other",
        address: {
          id: 1,
          street: "56158 Gracie Turnpike Apt. 962",
          streetName: "Chasity Turnpike",
          buildingNumber: "50071",
          city: "West Ryley",
          zipcode: "36986-5682",
          country: "Suriname",
          country_code: "SR",
          latitude: 42.912451,
          longitude: 77.098229,
        },
        website: "http://crist.info",
        image: "http://placeimg.com/640/480/people",
      },
    },
    {
      id: 6,
      name: "Hayes-Stracke",
      email: "brandt.effertz@hotmail.com",
      vat: "70714569789",
      phone: "+18209742709",
      country: "Germany",
      addresses: [
        {
          id: 1,
          street: "2430 Fay Vista",
          streetName: "Hodkiewicz Mills",
          buildingNumber: "529",
          city: "North Jack",
          zipcode: "31372",
          country: "Palestinian Territories",
          country_code: "PS",
          latitude: -39.339844,
          longitude: 147.796614,
        },
        {
          id: 1,
          street: "7249 Stanton Canyon Apt. 802",
          streetName: "Carolyn Burg",
          buildingNumber: "7323",
          city: "Erikatown",
          zipcode: "96023-5145",
          country: "Iceland",
          country_code: "IS",
          latitude: -75.99867,
          longitude: 159.822554,
        },
      ],
      website: "http://mraz.com",
      image: "http://placeimg.com/640/480/people",
      contact: {
        id: 1,
        firstname: "Destinee",
        lastname: "Upton",
        email: "triston38@yahoo.com",
        phone: "+17627396484",
        birthday: "1940-04-11",
        gender: "other",
        address: {
          id: 1,
          street: "6942 Anahi Courts",
          streetName: "Kristofer Forges",
          buildingNumber: "569",
          city: "Sanfordside",
          zipcode: "39914",
          country: "Kuwait",
          country_code: "KW",
          latitude: -47.93328,
          longitude: -121.880545,
        },
        website: "http://toy.biz",
        image: "http://placeimg.com/640/480/people",
      },
    },
    {
      id: 7,
      name: "Schroeder-Gleason",
      email: "crist.maggie@hotmail.com",
      vat: "55228972",
      phone: "+15039757131",
      country: "Sudan",
      addresses: [
        {
          id: 1,
          street: "775 Ernser Stravenue Suite 219",
          streetName: "Franecki Court",
          buildingNumber: "39176",
          city: "Carterhaven",
          zipcode: "47594-8119",
          country: "S\u00e3o Tom\u00e9 & Pr\u00edncipe",
          country_code: "ST",
          latitude: -52.457756,
          longitude: -175.973453,
        },
        {
          id: 1,
          street: "18349 June Isle Apt. 685",
          streetName: "Maybelle Route",
          buildingNumber: "645",
          city: "West Winfield",
          zipcode: "65126",
          country: "Guatemala",
          country_code: "GT",
          latitude: -15.331503,
          longitude: 155.624676,
        },
      ],
      website: "http://abernathy.com",
      image: "http://placeimg.com/640/480/people",
      contact: {
        id: 1,
        firstname: "Justen",
        lastname: "Koch",
        email: "wbashirian@yahoo.com",
        phone: "+15634541545",
        birthday: "1969-05-09",
        gender: "male",
        address: {
          id: 1,
          street: "499 Alfonso Pine",
          streetName: "Marks Street",
          buildingNumber: "88250",
          city: "Aritown",
          zipcode: "28524-0234",
          country: "Afghanistan",
          country_code: "AF",
          latitude: -69.788181,
          longitude: 56.799593,
        },
        website: "http://blanda.net",
        image: "http://placeimg.com/640/480/people",
      },
    },
    {
      id: 8,
      name: "Daugherty Inc",
      email: "sibyl49@kling.com",
      vat: "46301990797",
      phone: "+17257571187",
      country: "British Virgin Islands",
      addresses: [
        {
          id: 1,
          street: "604 Cummings Creek",
          streetName: "Michel Views",
          buildingNumber: "815",
          city: "D'Amoreborough",
          zipcode: "79607",
          country: "Germany",
          country_code: "DE",
          latitude: -7.002695,
          longitude: 107.05384,
        },
      ],
      website: "http://tremblay.info",
      image: "http://placeimg.com/640/480/people",
      contact: {
        id: 1,
        firstname: "Adonis",
        lastname: "Dietrich",
        email: "oconnell.eldridge@moen.com",
        phone: "+12235810093",
        birthday: "1979-05-18",
        gender: "other",
        address: {
          id: 1,
          street: "5661 Hermiston Club Suite 028",
          streetName: "Huel Mountain",
          buildingNumber: "4295",
          city: "West Solon",
          zipcode: "11314-8154",
          country: "Anguilla",
          country_code: "AI",
          latitude: -17.772718,
          longitude: -96.327017,
        },
        website: "http://schiller.com",
        image: "http://placeimg.com/640/480/people",
      },
    },
    {
      id: 9,
      name: "Bartell, Champlin and Ziemann",
      email: "casper.dibbert@gmail.com",
      vat: "12856739915",
      phone: "+13139741970",
      country: "Syrian Arab Republic",
      addresses: [
        {
          id: 1,
          street: "602 Hickle Lodge",
          streetName: "Lynch Springs",
          buildingNumber: "55514",
          city: "East Orlandohaven",
          zipcode: "15107-9983",
          country: "Caribbean Netherlands",
          country_code: "BQ",
          latitude: -59.182184,
          longitude: 101.079585,
        },
        {
          id: 1,
          street: "46666 Heller Rapid Apt. 595",
          streetName: "Mona Overpass",
          buildingNumber: "2322",
          city: "East Blake",
          zipcode: "33918-9122",
          country: "Sudan",
          country_code: "SD",
          latitude: -75.160877,
          longitude: 46.495024,
        },
        {
          id: 1,
          street: "36016 McLaughlin Hills Suite 586",
          streetName: "Kovacek Row",
          buildingNumber: "137",
          city: "Mauriciochester",
          zipcode: "90168-0067",
          country: "Japan",
          country_code: "JP",
          latitude: -44.831278,
          longitude: -127.417128,
        },
      ],
      website: "http://pfeffer.com",
      image: "http://placeimg.com/640/480/people",
      contact: {
        id: 1,
        firstname: "Rogelio",
        lastname: "Marvin",
        email: "kschinner@hotmail.com",
        phone: "+14639186239",
        birthday: "1941-03-07",
        gender: "male",
        address: {
          id: 1,
          street: "8504 Adrien Neck",
          streetName: "Ernestine Crescent",
          buildingNumber: "84759",
          city: "North Teresa",
          zipcode: "71724-0510",
          country: "Russia",
          country_code: "RU",
          latitude: -0.429706,
          longitude: -24.71764,
        },
        website: "http://zboncak.com",
        image: "http://placeimg.com/640/480/people",
      },
    },
    {
      id: 10,
      name: "Quigley, Steuber and Gibson",
      email: "idietrich@yahoo.com",
      vat: "16290507",
      phone: "+12532927072",
      country: "French Guiana",
      addresses: [
        {
          id: 1,
          street: "22034 Winona Ports Apt. 611",
          streetName: "Moore Dam",
          buildingNumber: "56843",
          city: "New Verniceburgh",
          zipcode: "92681-0976",
          country: "Chad",
          country_code: "TD",
          latitude: 39.404495,
          longitude: -90.402827,
        },
        {
          id: 1,
          street: "71418 Fadel Rue",
          streetName: "Christopher Street",
          buildingNumber: "48479",
          city: "Gradychester",
          zipcode: "99108",
          country: "Anguilla",
          country_code: "AI",
          latitude: -41.482858,
          longitude: -66.146233,
        },
        {
          id: 1,
          street: "4090 Rosenbaum Path Apt. 628",
          streetName: "Harber Tunnel",
          buildingNumber: "534",
          city: "West Minnieville",
          zipcode: "73200-8678",
          country: "South Africa",
          country_code: "ZA",
          latitude: 27.304074,
          longitude: -90.577547,
        },
        {
          id: 1,
          street: "534 Waelchi Light Apt. 849",
          streetName: "Gregoria Stream",
          buildingNumber: "90193",
          city: "Gabriellaton",
          zipcode: "14888-4317",
          country: "R\u00e9union",
          country_code: "RE",
          latitude: -76.767886,
          longitude: -126.081937,
        },
      ],
      website: "http://emmerich.com",
      image: "http://placeimg.com/640/480/people",
      contact: {
        id: 1,
        firstname: "Ken",
        lastname: "Dicki",
        email: "maci00@gmail.com",
        phone: "+19079005702",
        birthday: "1999-12-09",
        gender: "male",
        address: {
          id: 1,
          street: "76825 Keeling Highway",
          streetName: "Jasper Lane",
          buildingNumber: "77864",
          city: "Port Iliana",
          zipcode: "28013-2621",
          country: "Cocos (Keeling) Islands",
          country_code: "CC",
          latitude: 54.018701,
          longitude: -31.596259,
        },
        website: "http://dietrich.biz",
        image: "http://placeimg.com/640/480/people",
      },
    },
  ],
} as const;

export const getClientDetailsResponse = {
  status: "OK",
  code: 200,
  locale: "en_US",
  seed: null,
  data: {
    id: 101,
    firstname: "Marisol",
    lastname: "Reichert",
    email: "marisol.reichert@example.com",
    phone: "+14151231234",
    addresses: [
      {
        type: "billing",
        city: "East Alanamouth",
        country: "Canada",
      },
      {
        type: "shipping",
        city: "West Trevorview",
        country: "Canada",
      },
    ],
  },
};

export const dataTypesResponse = {
  array: ["hello", "world"],
  boolean: true,
  null: null,
  number: 123,
  object: { hello: "world" },
  string: "hello world",
  undefined,
};

export const getUserDetailsResponse = {
  meta: {
    subscriptionPlanOptions: [
      { value: "free", label: "Free" },
      { value: "pro", label: "Pro" },
      { value: "enterprise", label: "Enterprise" },
    ],
  },
  data: {
    status: "ok",
    userId: 101,
    accountBalance: 19.99,
    emailVerified: true,
    twoFactorEnabled: false,
    lastLogin: null,
    profile: { firstName: "Alice" },
    subscriptionPlan: "pro",
    recentActivity: ["login", 1623456789, false, null, { action: "purchase" }],
    membershipStartDate: "2023-06-15T09:30:00Z",
  },
};
