{{- if .Values.opentelemetry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-otel-collector
  labels:
    app: opentelemetry
    component: {{ include "direktiv.fullname" . }}-otel-collector
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  ports:
  - name: otlp-grpc # Default endpoint for OpenTelemetry gRPC receiver.
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http # Default endpoint for OpenTelemetry HTTP receiver.
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  selector:
    component: {{ include "direktiv.fullname" . }}-otel-collector
{{- end }}
