{{- if .Values.opentelemetry.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "direktiv.fullname" . }}-otel-collector-config
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
data:
  otel-collector-config: |
{{- .Values.opentelemetry.collectorconfig | nindent 4 }}
{{- end }}
