log_level : 'info'

package:
  deploy:
    components: 'direktiv'
    set:
      database_host: "postgres.default.svc"
      database_port: "5432"
      database_user: "admin"
      database_password: "password"
      database_dbname: "direktiv"
      database_sslmode: "disable"
      direktiv_replicas: "1"  
      direktiv_ingress_install: "false"
      direktiv_image: direktiv/direktiv
      direktiv_request_timeout: 14400
      direktiv_function_sizes: |
        limits:
          memory:
            small: 256
            medium: 512
            large: 1024
          cpu:
            small: 300m
            medium: 450m
            large: 700m
          disk:
            small: 128
            medium: 256
            large: 1024
      direktiv_fluentbit_config: |
        config:
          outputs: |
            [OUTPUT]
                name loki
                match  *
                host loki-gateway
                port 80
                labels app=direktiv
      direktiv_otel_config: |
        opentelemetry-collector:
          config:
            exporters:
              debug/noop:
                verbosity: normal
                sampling_initial: 0
                sampling_thereafter: 0
              debug: 
                verbosity: detailed
              otlp: 
                endpoint: "tempo:4317" 
                tls: 
                  insecure: true 
            service:
              telemetry:
                metrics:
                  level: none
              pipelines:
                logs: 
                  exporters:
                  - debug/noop
                metrics:
                  exporters:
                  - debug/noop
                traces: 
                  exporters:
                  - otlp
                  - debug
        
