FROM node:18.18.1 as build

ARG FULL_VERSION
ARG IS_ENTERPRISE=FALSE
ARG UI_BASE=/

RUN echo "building $FULL_VERSION"
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY . .

RUN --mount=type=cache,target=/root/.yarn YARN_CACHE_FOLDER=/root/.yarn yarn install

# If this causes problems on github actions: A potential fix is to change the builder image to `node:alpine`
RUN VITE_APP_VERSION=$FULL_VERSION VITE_BASE=${UI_BASE} VITE_IS_ENTERPRISE=${IS_ENTERPRISE} yarn build


