FROM openresty/openresty:1.21.4.3-2-focal

RUN ["luarocks", "install", "lua-resty-session", "3.10"]
RUN ["luarocks", "install", "lua-resty-http"]
RUN ["luarocks", "install", "lua-resty-jwt"]
RUN luarocks install lua-resty-openidc

ADD dist /usr/share/nginx/html
RUN echo '{ "response": "pong" }' > /usr/share/nginx/html/ping

COPY conf/prod/nginx.conf /etc/nginx/conf.d/default.conf