// Code generated by go-swagger; DO NOT EDIT.

package global_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGlobalServiceListParams creates a new GetGlobalServiceListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGlobalServiceListParams() *GetGlobalServiceListParams {
	return &GetGlobalServiceListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGlobalServiceListParamsWithTimeout creates a new GetGlobalServiceListParams object
// with the ability to set a timeout on a request.
func NewGetGlobalServiceListParamsWithTimeout(timeout time.Duration) *GetGlobalServiceListParams {
	return &GetGlobalServiceListParams{
		timeout: timeout,
	}
}

// NewGetGlobalServiceListParamsWithContext creates a new GetGlobalServiceListParams object
// with the ability to set a context for a request.
func NewGetGlobalServiceListParamsWithContext(ctx context.Context) *GetGlobalServiceListParams {
	return &GetGlobalServiceListParams{
		Context: ctx,
	}
}

// NewGetGlobalServiceListParamsWithHTTPClient creates a new GetGlobalServiceListParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGlobalServiceListParamsWithHTTPClient(client *http.Client) *GetGlobalServiceListParams {
	return &GetGlobalServiceListParams{
		HTTPClient: client,
	}
}

/* GetGlobalServiceListParams contains all the parameters to send to the API endpoint
   for the get global service list operation.

   Typically these are written to a http.Request.
*/
type GetGlobalServiceListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get global service list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGlobalServiceListParams) WithDefaults() *GetGlobalServiceListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get global service list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGlobalServiceListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get global service list params
func (o *GetGlobalServiceListParams) WithTimeout(timeout time.Duration) *GetGlobalServiceListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get global service list params
func (o *GetGlobalServiceListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get global service list params
func (o *GetGlobalServiceListParams) WithContext(ctx context.Context) *GetGlobalServiceListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get global service list params
func (o *GetGlobalServiceListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get global service list params
func (o *GetGlobalServiceListParams) WithHTTPClient(client *http.Client) *GetGlobalServiceListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get global service list params
func (o *GetGlobalServiceListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetGlobalServiceListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
