apiVersion: v2
name: direktiv
description: direktiv helm chart
icon: https://charts.direktiv.io/logo.png

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.29

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v0.8.9"

dependencies:
  - name: ingress-nginx
    repository: "https://kubernetes.github.io/ingress-nginx"
    version: "4.9.0"
    condition: ingress-nginx.install
  - name: fluent-bit
    repository: https://fluent.github.io/helm-charts
    version: 0.46.7
    condition: fluent-bit.install
  - name: nats
    repository: "https://nats-io.github.io/k8s/helm/charts"
    version: "1.2.6"
    condition: nats.install
  - name: opensearch
    repository: "https://opensearch-project.github.io/helm-charts/"
    version: "2.27.1"
    condition: opensearch.install
  - name: data-prepper
    repository: "https://opensearch-project.github.io/helm-charts/"
    version: "0.1.0"
    condition: data-prepper.install
