apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
  namespace: knative-serving
data:
  allow-container-concurrency-zero: "true"
  container-concurrency: "0"
  container-concurrency-max-limit: "1000"
  container-name-template: user-container
  enable-service-links: "false"
  max-revision-timeout-seconds: "7200"
  revision-cpu-limit: 1000m
  revision-cpu-request: 400m
  revision-ephemeral-storage-limit: 750M
  revision-ephemeral-storage-request: 500M
  revision-memory-limit: 200M
  revision-memory-request: 100M
  revision-timeout-seconds: "7200"
