apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "direktiv.fullname" . }}-api
  labels:
    {{- include "direktiv.labelsAPI" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "direktiv.selectorLabelsAPI" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "direktiv.selectorLabelsAPI" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 33333
        runAsGroup: 22222
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "direktiv.serviceAccountName" . }}
      containers:
{{- if .Values.opentelemetry.enabled }}
{{ include "direktiv.opentelemetry" . | indent 8 }}
{{- end }}
{{- if .Values.api.extraContainers }}
{{ toYaml .Values.api.extraContainers | indent 8}}
{{- end }}
        - name: api
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1048Mi"
              cpu: "2"
          image: "{{ .Values.registry }}/{{ .Values.api.image }}:{{ .Values.api.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          # command: ["/bin/server", "server", "/etc/direktiv/flow-config.yaml"]
          volumeMounts:
          {{- if .Values.api.extraVolumeMounts -}}
          {{ toYaml .Values.api.extraVolumeMounts | nindent 10 }}
          {{- end }}
          - name: flow-config
            mountPath: /etc/direktiv/flow-config.yaml
            subPath: flow-config.yaml
          ports:
            - name: api
              containerPort: 8080
              protocol: TCP
          env:
          - name: DIREKTIV_DEBUG
            value: {{ .Values.debug | quote }}
          - name: DIREKTIV_SERVICE_NAMESPACE
            value: {{ .Values.functions.namespace }}
          {{- if or (ne .Values.http_proxy "") (ne .Values.https_proxy "") }}
          - name: "HTTP_PROXY"
            value: "{{ .Values.http_proxy }}"
          - name: "HTTPS_PROXY"
            value: "{{ .Values.https_proxy }}"
          - name: "NO_PROXY"
            value: "{{ .Values.no_proxy }}"
          {{- end }}
          - name: DIREKTIV_DB
            valueFrom:
              secretKeyRef:
                name: {{ include "direktiv.fullname" . }}
                key: db
{{ include "direktiv.fluentbit" . | indent 8 }}
        # - name: fluentbit
        #   image: fluent/fluent-bit:1.8
        #   command: ["/fluent-bit/bin/fluent-bit", "-c", "/etc/fluentbit.cfg"]
        #   imagePullPolicy: {{ .Values.pullPolicy }}
        #   volumeMounts:
        #   - name: fluentcfg
        #     mountPath: /etc/fluentbit.cfg
        #     subPath: fluentbit.cfg
        #   securityContext:
        #     readOnlyRootFilesystem: true
        #     allowPrivilegeEscalation: false
        #   resources:
        #     requests:
        #       memory: "128Mi"
        #       cpu: "100m"
        #     limits:
        #       memory: "512Mi"
        #       cpu: "1"
        #   ports:
        #     - name: appport
        #       containerPort: 8889
        #       protocol: TCP
        #     - name: fnport
        #       containerPort: 8888
        #       protocol: TCP
        #   env:
        #   - name: PGSSLMODE
        #     value: {{ .Values.database.sslmode| quote }}
      volumes:
        {{- if .Values.api.extraVolumes }}
        {{ toYaml .Values.api.extraVolumes | nindent 8 }}
        {{- end }}
{{- if .Values.opentelemetry.enabled }}
{{ include "direktiv.opentelemetry.volume" . | indent 8 }}
{{- end }}
        - name: flow-config
          configMap:
            name: {{ include "direktiv.fullname" . }}-config-flow
        - name: fluentcfg
          configMap:
            name:  {{ include "direktiv.fullname" . }}-config-fluentbit
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
