// Code generated by go-swagger; DO NOT EDIT.

package variables

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteNamespaceVariableParams creates a new DeleteNamespaceVariableParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteNamespaceVariableParams() *DeleteNamespaceVariableParams {
	return &DeleteNamespaceVariableParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteNamespaceVariableParamsWithTimeout creates a new DeleteNamespaceVariableParams object
// with the ability to set a timeout on a request.
func NewDeleteNamespaceVariableParamsWithTimeout(timeout time.Duration) *DeleteNamespaceVariableParams {
	return &DeleteNamespaceVariableParams{
		timeout: timeout,
	}
}

// NewDeleteNamespaceVariableParamsWithContext creates a new DeleteNamespaceVariableParams object
// with the ability to set a context for a request.
func NewDeleteNamespaceVariableParamsWithContext(ctx context.Context) *DeleteNamespaceVariableParams {
	return &DeleteNamespaceVariableParams{
		Context: ctx,
	}
}

// NewDeleteNamespaceVariableParamsWithHTTPClient creates a new DeleteNamespaceVariableParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteNamespaceVariableParamsWithHTTPClient(client *http.Client) *DeleteNamespaceVariableParams {
	return &DeleteNamespaceVariableParams{
		HTTPClient: client,
	}
}

/*
DeleteNamespaceVariableParams contains all the parameters to send to the API endpoint

	for the delete namespace variable operation.

	Typically these are written to a http.Request.
*/
type DeleteNamespaceVariableParams struct {

	/* Namespace.

	   target namespace
	*/
	Namespace string

	/* Variable.

	   target variable
	*/
	Variable string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete namespace variable params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteNamespaceVariableParams) WithDefaults() *DeleteNamespaceVariableParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete namespace variable params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteNamespaceVariableParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete namespace variable params
func (o *DeleteNamespaceVariableParams) WithTimeout(timeout time.Duration) *DeleteNamespaceVariableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete namespace variable params
func (o *DeleteNamespaceVariableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete namespace variable params
func (o *DeleteNamespaceVariableParams) WithContext(ctx context.Context) *DeleteNamespaceVariableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete namespace variable params
func (o *DeleteNamespaceVariableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete namespace variable params
func (o *DeleteNamespaceVariableParams) WithHTTPClient(client *http.Client) *DeleteNamespaceVariableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete namespace variable params
func (o *DeleteNamespaceVariableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamespace adds the namespace to the delete namespace variable params
func (o *DeleteNamespaceVariableParams) WithNamespace(namespace string) *DeleteNamespaceVariableParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the delete namespace variable params
func (o *DeleteNamespaceVariableParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithVariable adds the variable to the delete namespace variable params
func (o *DeleteNamespaceVariableParams) WithVariable(variable string) *DeleteNamespaceVariableParams {
	o.SetVariable(variable)
	return o
}

// SetVariable adds the variable to the delete namespace variable params
func (o *DeleteNamespaceVariableParams) SetVariable(variable string) {
	o.Variable = variable
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteNamespaceVariableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param variable
	if err := r.SetPathParam("variable", o.Variable); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
