// Code generated by go-swagger; DO NOT EDIT.

package variables

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetWorkflowVariableReader is a Reader for the GetWorkflowVariable structure.
type GetWorkflowVariableReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWorkflowVariableReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetWorkflowVariableOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetWorkflowVariableOK creates a GetWorkflowVariableOK with default headers values
func NewGetWorkflowVariableOK() *GetWorkflowVariableOK {
	return &GetWorkflowVariableOK{}
}

/*
GetWorkflowVariableOK describes a response with status code 200, with default header values.

successfully got workflow variable
*/
type GetWorkflowVariableOK struct {
}

// IsSuccess returns true when this get workflow variable o k response has a 2xx status code
func (o *GetWorkflowVariableOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get workflow variable o k response has a 3xx status code
func (o *GetWorkflowVariableOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get workflow variable o k response has a 4xx status code
func (o *GetWorkflowVariableOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get workflow variable o k response has a 5xx status code
func (o *GetWorkflowVariableOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get workflow variable o k response a status code equal to that given
func (o *GetWorkflowVariableOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetWorkflowVariableOK) Error() string {
	return fmt.Sprintf("[GET /api/namespaces/{namespace}/tree/{workflow}?op=var][%d] getWorkflowVariableOK ", 200)
}

func (o *GetWorkflowVariableOK) String() string {
	return fmt.Sprintf("[GET /api/namespaces/{namespace}/tree/{workflow}?op=var][%d] getWorkflowVariableOK ", 200)
}

func (o *GetWorkflowVariableOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
