version: '3'

tasks:
  version:
    desc: Changes version of direktiv in zarf files
    cmds:
      - sed -e 's/VERSION/{{.VERSION}}/g' yolo/zarf.template.yaml > yolo/zarf.yaml
      - sed -e 's/VERSION/{{.VERSION}}/g' components/direktiv/yolo/zarf.template.yaml > components/direktiv/yolo/zarf.yaml
      - sed -e 's/VERSION/{{.VERSION}}/g' components/direktiv/zarf.template.yaml > components/direktiv/zarf.yaml
    requires:
      vars: [VERSION]
    internal: true

  yolo:
    desc: Builds yolo zarf package for direktiv and dependencies
    cmds: 
      - task: version
      - zarf package create yolo

