namespacePattern:
  type: string
  pattern: '^(([a-z][a-z0-9_\-\.]*[a-z0-9])|([a-z]))$' 

namespace:
  name: namespace
  in: path
  schema:
    $ref: '#/namespacePattern'
  required: true

serviceID:
  name: serviceID
  in: path
  schema:
    type: string
  required: true

podID:
  name: podID
  in: path
  schema:
    type: string
  required: true

registry:
  name: registry
  in: query
  schema:
    type: string
    # TODO: regex
  required: false

route-path:
  name: route-path
  in: path
  schema:
    type: string
  required: true