namespace:
  name: namespace
  in: path
  schema:
    type: string
    pattern: '^(([a-z][a-z0-9_\-\.]*[a-z0-9])|([a-z]))$' 
  required: true

serviceID:
  name: serviceID
  in: path
  schema:
    type: string
  required: true

podID:
  name: podID
  in: path
  schema:
    type: string
  required: true

pathRegistry:
  name: registry
  in: path
  schema:
    type: string
    # TODO: regex
  required: true

route-path:
  name: route-path
  in: path
  schema:
    type: string
  required: true