// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/direktiv/direktiv/pkg/flow/ent/annotation"
	"github.com/direktiv/direktiv/pkg/flow/ent/events"
	"github.com/direktiv/direktiv/pkg/flow/ent/instance"
	"github.com/direktiv/direktiv/pkg/flow/ent/instanceruntime"
	"github.com/direktiv/direktiv/pkg/flow/ent/namespace"
	"github.com/direktiv/direktiv/pkg/flow/ent/predicate"
	"github.com/google/uuid"
)

// InstanceQuery is the builder for querying Instance entities.
type InstanceQuery struct {
	config
	ctx                *QueryContext
	order              []OrderFunc
	inters             []Interceptor
	predicates         []predicate.Instance
	withNamespace      *NamespaceQuery
	withRuntime        *InstanceRuntimeQuery
	withChildren       *InstanceRuntimeQuery
	withEventlisteners *EventsQuery
	withAnnotations    *AnnotationQuery
	withFKs            bool
	modifiers          []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InstanceQuery builder.
func (iq *InstanceQuery) Where(ps ...predicate.Instance) *InstanceQuery {
	iq.predicates = append(iq.predicates, ps...)
	return iq
}

// Limit the number of records to be returned by this query.
func (iq *InstanceQuery) Limit(limit int) *InstanceQuery {
	iq.ctx.Limit = &limit
	return iq
}

// Offset to start from.
func (iq *InstanceQuery) Offset(offset int) *InstanceQuery {
	iq.ctx.Offset = &offset
	return iq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (iq *InstanceQuery) Unique(unique bool) *InstanceQuery {
	iq.ctx.Unique = &unique
	return iq
}

// Order specifies how the records should be ordered.
func (iq *InstanceQuery) Order(o ...OrderFunc) *InstanceQuery {
	iq.order = append(iq.order, o...)
	return iq
}

// QueryNamespace chains the current query on the "namespace" edge.
func (iq *InstanceQuery) QueryNamespace() *NamespaceQuery {
	query := (&NamespaceClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(instance.Table, instance.FieldID, selector),
			sqlgraph.To(namespace.Table, namespace.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, instance.NamespaceTable, instance.NamespaceColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRuntime chains the current query on the "runtime" edge.
func (iq *InstanceQuery) QueryRuntime() *InstanceRuntimeQuery {
	query := (&InstanceRuntimeClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(instance.Table, instance.FieldID, selector),
			sqlgraph.To(instanceruntime.Table, instanceruntime.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, instance.RuntimeTable, instance.RuntimeColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChildren chains the current query on the "children" edge.
func (iq *InstanceQuery) QueryChildren() *InstanceRuntimeQuery {
	query := (&InstanceRuntimeClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(instance.Table, instance.FieldID, selector),
			sqlgraph.To(instanceruntime.Table, instanceruntime.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, instance.ChildrenTable, instance.ChildrenColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEventlisteners chains the current query on the "eventlisteners" edge.
func (iq *InstanceQuery) QueryEventlisteners() *EventsQuery {
	query := (&EventsClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(instance.Table, instance.FieldID, selector),
			sqlgraph.To(events.Table, events.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, instance.EventlistenersTable, instance.EventlistenersColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAnnotations chains the current query on the "annotations" edge.
func (iq *InstanceQuery) QueryAnnotations() *AnnotationQuery {
	query := (&AnnotationClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(instance.Table, instance.FieldID, selector),
			sqlgraph.To(annotation.Table, annotation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, instance.AnnotationsTable, instance.AnnotationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Instance entity from the query.
// Returns a *NotFoundError when no Instance was found.
func (iq *InstanceQuery) First(ctx context.Context) (*Instance, error) {
	nodes, err := iq.Limit(1).All(setContextOp(ctx, iq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{instance.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (iq *InstanceQuery) FirstX(ctx context.Context) *Instance {
	node, err := iq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Instance ID from the query.
// Returns a *NotFoundError when no Instance ID was found.
func (iq *InstanceQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = iq.Limit(1).IDs(setContextOp(ctx, iq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{instance.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (iq *InstanceQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := iq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Instance entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Instance entity is found.
// Returns a *NotFoundError when no Instance entities are found.
func (iq *InstanceQuery) Only(ctx context.Context) (*Instance, error) {
	nodes, err := iq.Limit(2).All(setContextOp(ctx, iq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{instance.Label}
	default:
		return nil, &NotSingularError{instance.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (iq *InstanceQuery) OnlyX(ctx context.Context) *Instance {
	node, err := iq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Instance ID in the query.
// Returns a *NotSingularError when more than one Instance ID is found.
// Returns a *NotFoundError when no entities are found.
func (iq *InstanceQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = iq.Limit(2).IDs(setContextOp(ctx, iq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{instance.Label}
	default:
		err = &NotSingularError{instance.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (iq *InstanceQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := iq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Instances.
func (iq *InstanceQuery) All(ctx context.Context) ([]*Instance, error) {
	ctx = setContextOp(ctx, iq.ctx, "All")
	if err := iq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Instance, *InstanceQuery]()
	return withInterceptors[[]*Instance](ctx, iq, qr, iq.inters)
}

// AllX is like All, but panics if an error occurs.
func (iq *InstanceQuery) AllX(ctx context.Context) []*Instance {
	nodes, err := iq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Instance IDs.
func (iq *InstanceQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if iq.ctx.Unique == nil && iq.path != nil {
		iq.Unique(true)
	}
	ctx = setContextOp(ctx, iq.ctx, "IDs")
	if err = iq.Select(instance.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (iq *InstanceQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := iq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (iq *InstanceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, iq.ctx, "Count")
	if err := iq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, iq, querierCount[*InstanceQuery](), iq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (iq *InstanceQuery) CountX(ctx context.Context) int {
	count, err := iq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (iq *InstanceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, iq.ctx, "Exist")
	switch _, err := iq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (iq *InstanceQuery) ExistX(ctx context.Context) bool {
	exist, err := iq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InstanceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (iq *InstanceQuery) Clone() *InstanceQuery {
	if iq == nil {
		return nil
	}
	return &InstanceQuery{
		config:             iq.config,
		ctx:                iq.ctx.Clone(),
		order:              append([]OrderFunc{}, iq.order...),
		inters:             append([]Interceptor{}, iq.inters...),
		predicates:         append([]predicate.Instance{}, iq.predicates...),
		withNamespace:      iq.withNamespace.Clone(),
		withRuntime:        iq.withRuntime.Clone(),
		withChildren:       iq.withChildren.Clone(),
		withEventlisteners: iq.withEventlisteners.Clone(),
		withAnnotations:    iq.withAnnotations.Clone(),
		// clone intermediate query.
		sql:  iq.sql.Clone(),
		path: iq.path,
	}
}

// WithNamespace tells the query-builder to eager-load the nodes that are connected to
// the "namespace" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *InstanceQuery) WithNamespace(opts ...func(*NamespaceQuery)) *InstanceQuery {
	query := (&NamespaceClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withNamespace = query
	return iq
}

// WithRuntime tells the query-builder to eager-load the nodes that are connected to
// the "runtime" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *InstanceQuery) WithRuntime(opts ...func(*InstanceRuntimeQuery)) *InstanceQuery {
	query := (&InstanceRuntimeClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withRuntime = query
	return iq
}

// WithChildren tells the query-builder to eager-load the nodes that are connected to
// the "children" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *InstanceQuery) WithChildren(opts ...func(*InstanceRuntimeQuery)) *InstanceQuery {
	query := (&InstanceRuntimeClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withChildren = query
	return iq
}

// WithEventlisteners tells the query-builder to eager-load the nodes that are connected to
// the "eventlisteners" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *InstanceQuery) WithEventlisteners(opts ...func(*EventsQuery)) *InstanceQuery {
	query := (&EventsClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withEventlisteners = query
	return iq
}

// WithAnnotations tells the query-builder to eager-load the nodes that are connected to
// the "annotations" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *InstanceQuery) WithAnnotations(opts ...func(*AnnotationQuery)) *InstanceQuery {
	query := (&AnnotationClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withAnnotations = query
	return iq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Instance.Query().
//		GroupBy(instance.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (iq *InstanceQuery) GroupBy(field string, fields ...string) *InstanceGroupBy {
	iq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &InstanceGroupBy{build: iq}
	grbuild.flds = &iq.ctx.Fields
	grbuild.label = instance.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Instance.Query().
//		Select(instance.FieldCreatedAt).
//		Scan(ctx, &v)
func (iq *InstanceQuery) Select(fields ...string) *InstanceSelect {
	iq.ctx.Fields = append(iq.ctx.Fields, fields...)
	sbuild := &InstanceSelect{InstanceQuery: iq}
	sbuild.label = instance.Label
	sbuild.flds, sbuild.scan = &iq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a InstanceSelect configured with the given aggregations.
func (iq *InstanceQuery) Aggregate(fns ...AggregateFunc) *InstanceSelect {
	return iq.Select().Aggregate(fns...)
}

func (iq *InstanceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range iq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, iq); err != nil {
				return err
			}
		}
	}
	for _, f := range iq.ctx.Fields {
		if !instance.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if iq.path != nil {
		prev, err := iq.path(ctx)
		if err != nil {
			return err
		}
		iq.sql = prev
	}
	return nil
}

func (iq *InstanceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Instance, error) {
	var (
		nodes       = []*Instance{}
		withFKs     = iq.withFKs
		_spec       = iq.querySpec()
		loadedTypes = [5]bool{
			iq.withNamespace != nil,
			iq.withRuntime != nil,
			iq.withChildren != nil,
			iq.withEventlisteners != nil,
			iq.withAnnotations != nil,
		}
	)
	if iq.withNamespace != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, instance.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Instance).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Instance{config: iq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(iq.modifiers) > 0 {
		_spec.Modifiers = iq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, iq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := iq.withNamespace; query != nil {
		if err := iq.loadNamespace(ctx, query, nodes, nil,
			func(n *Instance, e *Namespace) { n.Edges.Namespace = e }); err != nil {
			return nil, err
		}
	}
	if query := iq.withRuntime; query != nil {
		if err := iq.loadRuntime(ctx, query, nodes, nil,
			func(n *Instance, e *InstanceRuntime) { n.Edges.Runtime = e }); err != nil {
			return nil, err
		}
	}
	if query := iq.withChildren; query != nil {
		if err := iq.loadChildren(ctx, query, nodes,
			func(n *Instance) { n.Edges.Children = []*InstanceRuntime{} },
			func(n *Instance, e *InstanceRuntime) { n.Edges.Children = append(n.Edges.Children, e) }); err != nil {
			return nil, err
		}
	}
	if query := iq.withEventlisteners; query != nil {
		if err := iq.loadEventlisteners(ctx, query, nodes,
			func(n *Instance) { n.Edges.Eventlisteners = []*Events{} },
			func(n *Instance, e *Events) { n.Edges.Eventlisteners = append(n.Edges.Eventlisteners, e) }); err != nil {
			return nil, err
		}
	}
	if query := iq.withAnnotations; query != nil {
		if err := iq.loadAnnotations(ctx, query, nodes,
			func(n *Instance) { n.Edges.Annotations = []*Annotation{} },
			func(n *Instance, e *Annotation) { n.Edges.Annotations = append(n.Edges.Annotations, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (iq *InstanceQuery) loadNamespace(ctx context.Context, query *NamespaceQuery, nodes []*Instance, init func(*Instance), assign func(*Instance, *Namespace)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Instance)
	for i := range nodes {
		if nodes[i].namespace_instances == nil {
			continue
		}
		fk := *nodes[i].namespace_instances
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(namespace.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "namespace_instances" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (iq *InstanceQuery) loadRuntime(ctx context.Context, query *InstanceRuntimeQuery, nodes []*Instance, init func(*Instance), assign func(*Instance, *InstanceRuntime)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Instance)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.InstanceRuntime(func(s *sql.Selector) {
		s.Where(sql.InValues(instance.RuntimeColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.instance_runtime
		if fk == nil {
			return fmt.Errorf(`foreign-key "instance_runtime" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "instance_runtime" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (iq *InstanceQuery) loadChildren(ctx context.Context, query *InstanceRuntimeQuery, nodes []*Instance, init func(*Instance), assign func(*Instance, *InstanceRuntime)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Instance)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.InstanceRuntime(func(s *sql.Selector) {
		s.Where(sql.InValues(instance.ChildrenColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.instance_children
		if fk == nil {
			return fmt.Errorf(`foreign-key "instance_children" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "instance_children" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (iq *InstanceQuery) loadEventlisteners(ctx context.Context, query *EventsQuery, nodes []*Instance, init func(*Instance), assign func(*Instance, *Events)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Instance)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Events(func(s *sql.Selector) {
		s.Where(sql.InValues(instance.EventlistenersColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.instance_eventlisteners
		if fk == nil {
			return fmt.Errorf(`foreign-key "instance_eventlisteners" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "instance_eventlisteners" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (iq *InstanceQuery) loadAnnotations(ctx context.Context, query *AnnotationQuery, nodes []*Instance, init func(*Instance), assign func(*Instance, *Annotation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Instance)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Annotation(func(s *sql.Selector) {
		s.Where(sql.InValues(instance.AnnotationsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.instance_annotations
		if fk == nil {
			return fmt.Errorf(`foreign-key "instance_annotations" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "instance_annotations" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (iq *InstanceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := iq.querySpec()
	if len(iq.modifiers) > 0 {
		_spec.Modifiers = iq.modifiers
	}
	_spec.Node.Columns = iq.ctx.Fields
	if len(iq.ctx.Fields) > 0 {
		_spec.Unique = iq.ctx.Unique != nil && *iq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, iq.driver, _spec)
}

func (iq *InstanceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(instance.Table, instance.Columns, sqlgraph.NewFieldSpec(instance.FieldID, field.TypeUUID))
	_spec.From = iq.sql
	if unique := iq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if iq.path != nil {
		_spec.Unique = true
	}
	if fields := iq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, instance.FieldID)
		for i := range fields {
			if fields[i] != instance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := iq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := iq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := iq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := iq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (iq *InstanceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(iq.driver.Dialect())
	t1 := builder.Table(instance.Table)
	columns := iq.ctx.Fields
	if len(columns) == 0 {
		columns = instance.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if iq.sql != nil {
		selector = iq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if iq.ctx.Unique != nil && *iq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range iq.modifiers {
		m(selector)
	}
	for _, p := range iq.predicates {
		p(selector)
	}
	for _, p := range iq.order {
		p(selector)
	}
	if offset := iq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := iq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (iq *InstanceQuery) ForUpdate(opts ...sql.LockOption) *InstanceQuery {
	if iq.driver.Dialect() == dialect.Postgres {
		iq.Unique(false)
	}
	iq.modifiers = append(iq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return iq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (iq *InstanceQuery) ForShare(opts ...sql.LockOption) *InstanceQuery {
	if iq.driver.Dialect() == dialect.Postgres {
		iq.Unique(false)
	}
	iq.modifiers = append(iq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return iq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (iq *InstanceQuery) Modify(modifiers ...func(s *sql.Selector)) *InstanceSelect {
	iq.modifiers = append(iq.modifiers, modifiers...)
	return iq.Select()
}

// InstanceGroupBy is the group-by builder for Instance entities.
type InstanceGroupBy struct {
	selector
	build *InstanceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (igb *InstanceGroupBy) Aggregate(fns ...AggregateFunc) *InstanceGroupBy {
	igb.fns = append(igb.fns, fns...)
	return igb
}

// Scan applies the selector query and scans the result into the given value.
func (igb *InstanceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, igb.build.ctx, "GroupBy")
	if err := igb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InstanceQuery, *InstanceGroupBy](ctx, igb.build, igb, igb.build.inters, v)
}

func (igb *InstanceGroupBy) sqlScan(ctx context.Context, root *InstanceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(igb.fns))
	for _, fn := range igb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*igb.flds)+len(igb.fns))
		for _, f := range *igb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*igb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := igb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// InstanceSelect is the builder for selecting fields of Instance entities.
type InstanceSelect struct {
	*InstanceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (is *InstanceSelect) Aggregate(fns ...AggregateFunc) *InstanceSelect {
	is.fns = append(is.fns, fns...)
	return is
}

// Scan applies the selector query and scans the result into the given value.
func (is *InstanceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, is.ctx, "Select")
	if err := is.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InstanceQuery, *InstanceSelect](ctx, is.InstanceQuery, is, is.inters, v)
}

func (is *InstanceSelect) sqlScan(ctx context.Context, root *InstanceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(is.fns))
	for _, fn := range is.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*is.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := is.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (is *InstanceSelect) Modify(modifiers ...func(s *sql.Selector)) *InstanceSelect {
	is.modifiers = append(is.modifiers, modifiers...)
	return is
}
