apiVersion: v1
data:
  blocklist: |-
    ["grafana", "tempo", "loki", "auth"]
kind: ConfigMap
metadata:
  name: api-blocklistnamespaces-cm
  labels:
    {{ include "direktiv.labelsAPI" . | nindent 4 }}-api
