apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "direktiv.fullname" . }}-config-api
  labels:
    {{ include "direktiv.labelsAPI" . | nindent 4 }}-api
data:
  api-config.yaml: |

      blocklist: "/blocklist"
      templates:
        workflowTemplateDirectories:
        - name: default
          directory: "/tmp/workflow-templates"
        actionTemplateDirectories:
        - name: default
          directory: "/tmp/action-templates"
