{{- if .Values.apikey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "direktiv.fullname" . }}-apikey
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
type: Opaque
data:
   kongCredType: {{ "key-auth" | b64enc | quote }}
   key: {{ .Values.apikey | b64enc | quote }}
{{- end }}
