{{- if .Values.apikey }}
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: {{ include "direktiv.fullname" . }}-api-user
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
username: direktiv-api-user
credentials:
- {{ include "direktiv.fullname" . }}-apikey
{{- end }}
