{{- if .Values.withFlow -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-ingress-hl
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 6666
      name: ingress
      protocol: TCP
  selector:
    {{- include "direktiv.selectorLabels" . | nindent 4 }}
{{- end }}
