{{- if .Values.withFlow -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-vars
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    # konghq.com/plugins: {{ include "direktiv.fullname" . }}-kong-plugin-grpc-gateway
    konghq.com/protocol: "http"
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 9999
      name: vars
      protocol: TCP
  selector:
    {{- include "direktiv.selectorLabels" . | nindent 4 }}
{{- end }}
