apiVersion: v1
kind: ConfigMap
metadata:
  name: flow-cm-config
data:
  default.toml: |    
    [InstanceLogging]
      Driver = {{ .Values.logDriver | quote }}
    
    [flowAPI]
      Bind = "0.0.0.0:7777"
      Endpoint = "dns2:///{{ include "direktiv.fullname" . }}-flow-hl.{{ .Release.Namespace }}:7777"
      MaxScale = {{ .Values.flow.maxScale }}
      Protocol = {{ .Values.flow.protocol | quote }}
      Sidecar = {{ .Values.flow.sidecar | quote }}
    
    [ingressAPI]
      Bind = "0.0.0.0:6666"
      Endpoint = "dns2:///{{ include "direktiv.fullname" . }}-ingress-hl.{{ .Release.Namespace }}:6666"
    
    [isolates]
    {{- if .Values.isolates.podCleaner }}
      CleanupPods = 1
    {{- else }}
      CleanupPods = 0
    {{- end }}

