{{- if .Values.withFlow -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-flow
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  ports:
    - port: 7777
      name: flow
      protocol: TCP
  selector:
    {{- include "direktiv.selectorLabels" . | nindent 4 }}
{{- end }}
