apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "direktiv.fullname" . }}-config-functions
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
data:
  functions-config.yaml: |

      # name of the service account to run the pods
      service-account: {{ include "direktiv.serviceAccountName" . }}-functions-pod

      # name of the namespace to use for the services/functions
      namespace: {{ .Values.functions.namespace }}

      # db secret for pub/sub
      sidecar-db: {{ include "direktiv.fullname" . }}-secrets-functions

      # pod sidecar name
      sidecar: {{ .Values.functions.sidecar }}

      # init pod name
      init-pod: {{ .Values.functions.initPodImage }}

      # tls secret for init pod
      init-pod-certificate: {{ .Values.functions.initPodCertificate }}

      # max number of revisions to keep per namespace or global
      keep-revisions: 3

      # max number of parallel jobs per namespace
      max-jobs: 5

      # kubernetes 1.20 auto cleans up jobs, for < 1.19, should be enabled
      pod-cleaner: {{ .Values.functions.podCleaner }}

      # max number of pods per service
      max-scale: 3

      # rollout seconds for knative services
      rollout-duration: 300

      # shaping network traffic if supported by network plugin
      net-shape: {{ .Values.functions.netShape }}

      # default concurrency level
      concurrency: 100

      # max ephemeral storage in MB
      storage: 100

      # runtime for services, e.g. gvisor
      runtime: {{ .Values.functions.runtime }}

      # memory/cpu value defined for different service sizes
      memory:
        small: 128
        medium: 512
        large: 1024
      cpu:
        small: 0.25
        medium: 0.5
        large: 1.0

      # proxy values
      proxy:
        no: ""
        https: ""
        http: ""

      grpc-config: {{ include "direktiv.fullname" . }}-config-grpc

      # additional sidecar containers
      additionalContainers:
{{- if .Values.functions.extraContainersPod }}
{{ toYaml .Values.functions.extraContainersPod | indent 8}}
{{- end }}
