apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "direktiv.serviceAccountName" . }}-isolate-pod
  namespace: {{ .Values.isolates.namespace }}
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
