apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-isolates-hl
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 5555
      name: grpc
      protocol: TCP
  selector:
    {{- include "direktiv.selectorLabels" . | nindent 4 }}-isolates
