kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-sidecar-grpc
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      direktiv-app: direktiv
  ingress:
  - from:
    - namespaceSelector:
        matchExpressions:
          - { key: serving.knative.dev/release, operator: Exists }
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "direktiv.name" . }}
    ports:
      - port: 8890
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
