kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-api-grpc
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "direktiv.name" . }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "direktiv.name" . }}-api
    ports:
      - port: 6666
  - from:
    - podSelector:
        matchLabels:
          direktiv-app: direktiv
    ports:
      - port: 7777
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
