{{- if .Values.useNetworkPolicies -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-lb-ingress
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "direktiv.name" . }}-api
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: envoy
      namespaceSelector:
        matchLabels:
          networking.knative.dev/ingress-provider: contour
    ports:
      - port: 8080
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
{{- end }}
