{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-prometheus-service
  labels:
    {{- include "direktiv.labelsPrometheus" . | nindent 4 }}
  annotations:
    projectcontour.io/upstream-protocol.tls: "{{ include "direktiv.fullname" . }}-prometheus-service,9090"
spec:
  selector:
    {{- include "direktiv.selectorLabelsPrometheus" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
{{- end }}
