{{- if .Values.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "direktiv.fullname" . }}-prometheus
  labels:
      {{ include "direktiv.labelsPrometheus" . | nindent 4 }}-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "direktiv.selectorLabelsPrometheus" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "direktiv.selectorLabelsPrometheus" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "direktiv.serviceAccountName" . }}-prometheus
      securityContext:
        runAsNonRoot: true
      containers:
        - name: prometheus
          image: prom/prometheus:v2.29.2
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          emptyDir: {}
{{- end }}