kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ include "direktiv.serviceAccountName" . }}-binding
subjects:
- kind: ServiceAccount
  name: {{ include "direktiv.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
 kind: Role
 name: {{ include "direktiv.serviceAccountName" . }}-role-ns
 apiGroup: rbac.authorization.k8s.io
