kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ include "direktiv.serviceAccountName" . }}-role
 labels:
   {{- include "direktiv.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["serving.knative.dev"]
  resources: ["*"]
  verbs: ["*"]
