kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ include "direktiv.serviceAccountName" . }}-role-ns
 labels:
   {{- include "direktiv.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
