{{- if (eq .Values.withFlow true)}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "direktiv.fullname" . }}-isolate
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}-isolate
type: Opaque
data:
  exchangeKey: {{ .Values.flow.exchange | b64enc | quote }}
  {{- if .Values.db }}
  db: {{ .Values.db | b64enc | quote }}
  {{- else }}
  db: {{ printf "host=%s-support port=5432 user=direktiv dbname=direktiv password=direktivdirektiv sslmode=disable" ( include "direktiv.fullname" . ) | b64enc | quote }}
  {{- end }}
  {{- end }}
