kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ include "direktiv.serviceAccountName" . }}-sidecar-binding
subjects:
- kind: ServiceAccount
  name: {{ include "direktiv.serviceAccountName" . }}-sidecar
  namespace: {{ .Release.Namespace }}
roleRef:
 kind: Role
 name: {{ include "direktiv.serviceAccountName" . }}-sidecar-role
 apiGroup: rbac.authorization.k8s.io
