{{- if .Values.withSupport -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "direktiv.fullname" . }}-support
  labels:
    {{- include "direktiv.labelsSupport" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "direktiv.selectorLabelsSupport" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "direktiv.selectorLabelsSupport" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "direktiv.serviceAccountName" . }}
      {{- if .Values.supportPersist }}
      volumes:
      - name: pg-vol
        hostPath:
          path: /tmp/pg
      {{- end }}
      containers:
        - name: postgres
          image: postgres:12.6-alpine
          {{- if .Values.supportPersist }}
          volumeMounts:
          - name: pg-vol
            mountPath: /var/lib/postgresql/data
          {{- end }}
          env:
          - name: POSTGRES_USER
            value: "direktiv"
          - name: POSTGRES_PASSWORD
            value: "direktivdirektiv"
          - name: POSTGRES_DB
            value: "direktiv"
          ports:
            - containerPort: 5432
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
