apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "direktiv.fullname" . }}-config-tls
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
data:
  grpc-config.yaml: |

      # configuration information which components are tls/mtls
      flow-tls = enabled

      ingress-tls = enabled
