apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: direktiv-knative
  namespace: knative-serving
spec:
  version: "1.17.0"
  registry: 
    override:
      cleanup-serving-/cleanup: gcr.io/knative-releases/knative.dev/serving/pkg/cleanup/cmd/cleanup@sha256:7f30007b363feabe1bae97c3959d02b77ccc32f03a046066142c900378ca72a2
      storage-version-migration-serving-/migrate: gcr.io/knative-releases/knative.dev/pkg/apiextensions/storageversion/cmd/migrate@sha256:8ba29e808708a2acd31c7f5b463aa181c6d1c5d468a618f00f4bcf9c2377fa40
      activator: gcr.io/knative-releases/knative.dev/serving/cmd/activator@sha256:044452b549edf0ecc6e3e6a778c3902bc1e28973ea5c6503e0ab9e61918d8e08
      autoscaler: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler@sha256:1c81d51190dd0aa27f08ae7c9c60bc07ea68de94f670e7f4798c1fba30c77d4e
      controller: gcr.io/knative-releases/knative.dev/serving/cmd/controller@sha256:fb6ed2b105670e3b53abfdf80b30cc71c8e352f6ef65a43ef7d78ec2b1e9e955
      webhook: gcr.io/knative-releases/knative.dev/serving/cmd/webhook@sha256:a2f2fcc360ca735ac3444e62b62477fda0d0475e702a4571b554f02d7380cbc0
      autoscaler-hpa: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler-hpa@sha256:97cd60a00dc51750ca03e6f28451d98ee016b7bcf381de5b0aebd23937a62d4a
      net-contour-controller/controller: gcr.io/knative-releases/knative.dev/net-contour/cmd/controller@sha256:42e88a78585e5a47b07ada5b1b0abfb4293731ce71877714aac2c9fb11be0c83
      queue-proxy: gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:f9779359ec560349596eea99a7446eac0db2436339e0586a3656c978b95b0266
  high-availability:
    replicas: 1
  ingress:
    contour:
      enabled: true
  deployments:
  - name: activator
    annotations:
      linkerd.io/inject: enabled
  - name: controller
    annotations:
      linkerd.io/inject: enabled
    env:
    - container: controller
      envVars:
      - name: HTTP_PROXY
        value: "###ZARF_VAR_KNATIVE_HTTP_PROXY###"
      - name: HTTPS_PROXY
        value: "###ZARF_VAR_KNATIVE_HTTPS_PROXY###"
      - name: NO_PROXY
        value: "###ZARF_VAR_KNATIVE_NO_PROXY###"
  config:
    features:
      multi-container: "enabled"  
      kubernetes.podspec-affinity: "enabled"
      kubernetes.podspec-topologyspreadconstraints: "enabled"
      kubernetes.podspec-hostaliases: "disabled"
      kubernetes.podspec-nodeselector: "enabled"
      kubernetes.podspec-tolerations: "enabled"
      kubernetes.podspec-fieldref: "disabled"
      kubernetes.podspec-runtimeclassname: "enabled"
      kubernetes.podspec-dnspolicy: "disabled"
      kubernetes.podspec-dnsconfig: "disabled"
      kubernetes.podspec-securitycontext: "enabled"
      kubernetes.podspec-priorityclassname: "enabled"
      kubernetes.podspec-schedulername: "disabled"
      kubernetes.containerspec-addcapabilities: "disabled"
      kubernetes.podspec-dryrun: "allowed"
      tag-header-based-routing: "enabled"
      autodetect-http2: "enabled"
      kubernetes.podspec-volumes-emptydir: "enabled"
      kubernetes.podspec-init-containers: "enabled"
      kubernetes.podspec-persistent-volume-claim: "disabled"
      kubernetes.podspec-persistent-volume-write: "disabled"
      queueproxy.mount-podinfo: "disabled"
    autoscaler:
      container-concurrency-target-percentage: "70"
      container-concurrency-target-default: "100"
      requests-per-second-target-default: "200"
      target-burst-capacity: "211"
      stable-window: "60s"
      panic-window-percentage: "10.0"
      panic-threshold-percentage: "200.0"
      max-scale-up-rate: "1000.0"
      max-scale-down-rate: "2.0"
      enable-scale-to-zero: "true"
      scale-to-zero-grace-period: 120s
      scale-to-zero-pod-retention-period: 120s
      pod-autoscaler-class: "kpa.autoscaling.knative.dev"
      activator-capacity: "100.0"
      initial-scale: "0"
      allow-zero-initial-scale: "true"
      min-scale: "0"
      max-scale: "1"
      scale-down-delay: "0s"
      max-scale-limit: "10"
    defaults:
      revision-timeout-seconds: "14400"
      max-revision-timeout-seconds: "14400"
      revision-response-start-timeout-seconds: "14400"
      revision-idle-timeout-seconds: "0"
      revision-cpu-request: "50m"
      revision-memory-request: "100M"
      revision-ephemeral-storage-request: "50M"
      revision-cpu-limit: "1000m"
      revision-memory-limit: "2048M"
      revision-ephemeral-storage-limit: "4096M"
      container-name-template: "user-container"
      init-container-name-template: "init-container"
      container-concurrency: "0"
      container-concurrency-max-limit: "1000"
      allow-container-concurrency-zero: "true"
      enable-service-links: "false"
    deployment:
      registries-skipping-tag-resolving: "kind.local,ko.local,dev.local,localhost:5000,localhost:31212"
      queue-sidecar-image: gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:f9779359ec560349596eea99a7446eac0db2436339e0586a3656c978b95b0266
      digest-resolution-timeout: "10s"
      progress-deadline: "600s"
      queue-sidecar-cpu-request: "25m"
      queue-sidecar-cpu-limit: "1000m"
      queue-sidecar-memory-request: "400Mi"
      queue-sidecar-memory-limit: "800Mi"
      queue-sidecar-ephemeral-storage-request: "512Mi"
      queue-sidecar-ephemeral-storage-limit: "1024Mi"
    network:
      ingress-class: "contour.ingress.networking.knative.dev"


