// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateNamespaceServiceBody CreateNamespaceServiceBody create namespace service body
// Example: {"cmd":"","image":"vorteil/request:v12","minScale":"1","name":"fast-request","size":"small"}
//
// swagger:model CreateNamespaceServiceBody
type CreateNamespaceServiceBody struct {

	// cmd
	// Required: true
	Cmd *string `json:"cmd"`

	// Target image a service will use
	// Required: true
	Image *string `json:"image"`

	// Minimum amount of service pods to be live
	// Required: true
	MinScale *int64 `json:"minScale"`

	// Name of new service
	// Required: true
	Name *string `json:"name"`

	// Size of created service pods
	// Required: true
	// Enum: [[small medium large]]
	Size *string `json:"size"`
}

// Validate validates this create namespace service body
func (m *CreateNamespaceServiceBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCmd(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMinScale(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSize(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateNamespaceServiceBody) validateCmd(formats strfmt.Registry) error {

	if err := validate.Required("cmd", "body", m.Cmd); err != nil {
		return err
	}

	return nil
}

func (m *CreateNamespaceServiceBody) validateImage(formats strfmt.Registry) error {

	if err := validate.Required("image", "body", m.Image); err != nil {
		return err
	}

	return nil
}

func (m *CreateNamespaceServiceBody) validateMinScale(formats strfmt.Registry) error {

	if err := validate.Required("minScale", "body", m.MinScale); err != nil {
		return err
	}

	return nil
}

func (m *CreateNamespaceServiceBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

var createNamespaceServiceBodyTypeSizePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["[small medium large]"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createNamespaceServiceBodyTypeSizePropEnum = append(createNamespaceServiceBodyTypeSizePropEnum, v)
	}
}

const (

	// CreateNamespaceServiceBodySizeSmallMediumLarge captures enum value "[small medium large]"
	CreateNamespaceServiceBodySizeSmallMediumLarge string = "[small medium large]"
)

// prop value enum
func (m *CreateNamespaceServiceBody) validateSizeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, createNamespaceServiceBodyTypeSizePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CreateNamespaceServiceBody) validateSize(formats strfmt.Registry) error {

	if err := validate.Required("size", "body", m.Size); err != nil {
		return err
	}

	// value enum
	if err := m.validateSizeEnum("size", "body", *m.Size); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create namespace service body based on context it is used
func (m *CreateNamespaceServiceBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateNamespaceServiceBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateNamespaceServiceBody) UnmarshalBinary(b []byte) error {
	var res CreateNamespaceServiceBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
