// Code generated by go-swagger; DO NOT EDIT.

package other

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ReplayCloudeventReader is a Reader for the ReplayCloudevent structure.
type ReplayCloudeventReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplayCloudeventReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReplayCloudeventOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewReplayCloudeventOK creates a ReplayCloudeventOK with default headers values
func NewReplayCloudeventOK() *ReplayCloudeventOK {
	return &ReplayCloudeventOK{}
}

/*
ReplayCloudeventOK describes a response with status code 200, with default header values.

successfully replayed cloud event
*/
type ReplayCloudeventOK struct {
}

// IsSuccess returns true when this replay cloudevent o k response has a 2xx status code
func (o *ReplayCloudeventOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this replay cloudevent o k response has a 3xx status code
func (o *ReplayCloudeventOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this replay cloudevent o k response has a 4xx status code
func (o *ReplayCloudeventOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this replay cloudevent o k response has a 5xx status code
func (o *ReplayCloudeventOK) IsServerError() bool {
	return false
}

// IsCode returns true when this replay cloudevent o k response a status code equal to that given
func (o *ReplayCloudeventOK) IsCode(code int) bool {
	return code == 200
}

func (o *ReplayCloudeventOK) Error() string {
	return fmt.Sprintf("[POST /api/namespaces/{namespace}/events/{event}/replay][%d] replayCloudeventOK ", 200)
}

func (o *ReplayCloudeventOK) String() string {
	return fmt.Sprintf("[POST /api/namespaces/{namespace}/events/{event}/replay][%d] replayCloudeventOK ", 200)
}

func (o *ReplayCloudeventOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
