registry: localhost:5000
pullPolicy: Always
debug: "true"

secrets:
  image: "secrets"
  tag: "latest"

flow:
  image: "flow"
  tag: "latest"

ui:
  image: "direktiv-ui"
  tag: "latest"

api:
  image: "api"
  tag: "latest"

functions:
  namespace: direktiv-services-direktiv
  image: "functions"
  tag: "latest"
  sidecar: "localhost:5000/sidecar"
  initPodImage: "localhost:5000/direktiv-init-pod"

opentelemetry:
  address: "host"
  enabled: true
  agentconfig: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      otlp:
        endpoint: "direktiv-otel-collector.default:4317"
        insecure: true
        sending_queue:
          num_consumers: 4
          queue_size: 100
        retry_on_failure:
          enabled: true
    processors:
      batch:
      memory_limiter:
        # Same as --mem-ballast-size-mib CLI argument
        ballast_size_mib: 165
        # 80% of maximum memory up to 2G
        limit_mib: 400
        # 25% of limit up to 2G
        spike_limit_mib: 100
        check_interval: 5s
    extensions:
      zpages: {}
    service:
      extensions: [zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]
  # -- config for collector
  collectorconfig: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
      memory_limiter:
        # Same as --mem-ballast-size-mib CLI argument
        ballast_size_mib: 683
        # 80% of maximum memory up to 2G
        limit_mib: 1500
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s
    extensions:
      zpages: {}
    exporters:
      otlp:
        endpoint: "192.168.1.113:4317"
        insecure: true
      logging:
        loglevel: debug
      # jaeger:
      #   endpoint: "http://192.168.1.113:14250"
      #   insecure: true
    service:
      extensions: [zpages]
      pipelines:
        traces/1:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging, otlp]
