registry: localhost:5000
pullPolicy: Always
debug: "true"

secrets:
  image: "secrets"
  tag: "latest"

flow:
  image: "flow"
  dbimage: "flow-dbinit"
  tag: "latest"

ui:
  image: "ui"
  tag: "latest"

api:
  image: "api"
  tag: "latest"
  
functions:
  namespace: direktiv-services-direktiv
  image: "functions"
  tag: "latest"
  sidecar: "sidecar"
  initPodImage: "init-pod"

database:
  host: "direktiv-primary.postgres.svc"
  port: 5432
  user: "direktiv"
  password: "DJ6WGdS713eaFsij^xmwjPI}"
  name: "direktiv"
  sslmode: require

database:
  host: "direktiv-primary.postgres.svc"
  port: 5432
  user: "direktiv"
  password: "-WbvkBu>}..[Ak_9BQfM+-X3"
  name: "direktiv"
  sslmode: require

database:
  host: "direktiv-primary.postgres.svc"
  port: 5432
  user: "direktiv"
  password: "h/Hfsfq9<|TAsiyhY0B5.^We"
  name: "direktiv"
  sslmode: require

database:
  host: "direktiv-primary.postgres.svc"
  port: 5432
  user: "direktiv"
  password: ")L=*bz^IVSgyj1l?c;5g])JO"
  name: "direktiv"
  sslmode: require

database:
  host: "direktiv-primary.postgres.svc"
  port: 5432
  user: "direktiv"
  password: ".-s6gz7=:)/gf;)7S=D.MDK1"
  name: "direktiv"
  sslmode: require

database:
  host: "direktiv-primary.postgres.svc"
  port: 5432
  user: "direktiv"
  password: "2izl}7|9mMqfemb8-ooZJC2k"
  name: "direktiv"
  sslmode: require
