registry: localhost:5000
pullPolicy: Always
debug: "true"

secrets:
  image: "secrets"
  tag: "latest"

flow:
  image: "flow"
  dbimage: "flow-dbinit"
  tag: "latest"

ui:
  image: "ui"
  tag: "latest"

api:
  image: "api"
  tag: "latest"

functions:
  namespace: direktiv-services-direktiv
  image: "functions"
  tag: "latest"
  sidecar: "sidecar"
  initPodImage: "init-pod"

# opentelemetry:
#   enabled: true
#   address: tempo-tempo-distributed-distributor.tempo:4317
#   address: "localhost:4317"
#   agentconfig: |
#     receivers:
#       otlp:
#         protocols:
#           grpc:
#           http:
#     exporters:
#       otlp:
#         endpoint: "192.168.1.113:4317"
#         insecure: true
#         sending_queue:
#           num_consumers: 4
#           queue_size: 100
#         retry_on_failure:
#           enabled: true
#       logging:
#         loglevel: debug
#     processors:
#       batch:
#       memory_limiter:
#         # Same as --mem-ballast-size-mib CLI argument
#         ballast_size_mib: 165
#         # 80% of maximum memory up to 2G
#         limit_mib: 400
#         # 25% of limit up to 2G
#         spike_limit_mib: 100
#         check_interval: 5s
#     extensions:
#       zpages: {}
#     service:
#       extensions: [zpages]
#       pipelines:
#         traces:
#           receivers: [otlp]
#           processors: [memory_limiter, batch]
#           exporters: [logging, otlp]

database:
  host: "direktiv-primary.postgres.svc"
  port: 5432
  user: "direktiv"
  password: "bo*BzUu+bnoeF*+/msNY8SP="
  name: "direktiv"
  sslmode: require

