registry: localhost:5000
pullPolicy: Always
debug: "true"

secrets:
  image: secrets
flow:
  image: flow
  sidecar: "localhost:5000/sidecar"
  initPod: "localhost:5000/init-pod"
ui:
  image: direktiv-ui
api:
  image: api
