flow:
  logging: json

fluent-bit:
  install: true
  envFrom:
    - secretRef:
        name: direktiv-fluentbit
  config:
    inputs: |
      [INPUT]
          Name                    tail
          Path                    /var/log/containers/*flow*.log,/var/log/containers/*direktiv-sidecar*.log
          Mem_Buf_Limit           5MB
          Skip_Long_Lines         Off
          Tag                     input
          multiline.parser        cri, docker
          Refresh_Interval        1
          Buffer_Max_Size         64k
    outputs: |
      [OUTPUT]
          name                    pgsql
          match                   flow.*
          port                    ${PG_PORT}
          table                   fluentbit
          user                    ${PG_USER}
          database                ${PG_DB_NAME}
          host                    ${PG_HOST}
          password                ${PG_PASSWORD}

      [OUTPUT]
          Name                    loki
          Match                   *
          Host                    loki.default
          Port                    3100
          Labels                  job=fluentbit
          Line_Format             json
    filters: |
      [FILTER]
          Name                    rewrite_tag
          Match                   input
          Rule                    $log ^.*"track":"([^"]*).*$ flow.$1 true
      [FILTER]
          Name parser
          Match *
          Parser json
          Key_Name log
          Reserve_Data on
opentelemetry:
  # -- opentelemetry address where Direktiv is sending data to
  address: "tempo.default:4317"
  # -- installs opentelemtry agent as sidecar in flow
  enabled: true
  # -- config for sidecar agent
  agentconfig: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      otlp:
        endpoint: "tempo.default:4317"
        insecure: true
        sending_queue:
          num_consumers: 4
          queue_size: 100
        retry_on_failure:
          enabled: true
      logging:
        loglevel: debug
    processors:
      batch:
      memory_limiter:
        # Same as --mem-ballast-size-mib CLI argument
        ballast_size_mib: 165
        # 80% of maximum memory up to 2G
        limit_mib: 400
        # 25% of limit up to 2G
        spike_limit_mib: 100
        check_interval: 5s
    extensions:
      zpages: {}
    service:
      extensions: [zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging, otlp]
