{{- if .Values.networkPolicies.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nwp-functions
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "direktiv.name" . }}-functions
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "direktiv.name" . }}
      ports:
        - port: 5555
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "direktiv.name" . }}-api
      ports:
        - port: 5555
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    {{- if .Values.withSupport }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "direktiv.name" . }}-support
      ports:
        - port: 5432
    {{- end }}
    {{- if ne .Values.networkPolicies.db "" }}
    - to:
        - ipBlock:
            cidr: {{ .Values.networkPolicies.db }}
      ports:
        - port: 5432
    {{- end }}
    - to:
        - ipBlock:
            cidr: {{ .Values.networkPolicies.podCidr }}
        - ipBlock:
            cidr: {{ .Values.networkPolicies.serviceCidr }}
      ports:
        - port: 443
        - port: 8080
        - port: 80
{{- end }}
