// Code generated by go-swagger; DO NOT EDIT.

package workflow_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteWorkflowServiceReader is a Reader for the DeleteWorkflowService structure.
type DeleteWorkflowServiceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteWorkflowServiceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteWorkflowServiceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteWorkflowServiceOK creates a DeleteWorkflowServiceOK with default headers values
func NewDeleteWorkflowServiceOK() *DeleteWorkflowServiceOK {
	return &DeleteWorkflowServiceOK{}
}

/*
DeleteWorkflowServiceOK describes a response with status code 200, with default header values.

successfully deleted service
*/
type DeleteWorkflowServiceOK struct {
}

// IsSuccess returns true when this delete workflow service o k response has a 2xx status code
func (o *DeleteWorkflowServiceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete workflow service o k response has a 3xx status code
func (o *DeleteWorkflowServiceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete workflow service o k response has a 4xx status code
func (o *DeleteWorkflowServiceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete workflow service o k response has a 5xx status code
func (o *DeleteWorkflowServiceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete workflow service o k response a status code equal to that given
func (o *DeleteWorkflowServiceOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteWorkflowServiceOK) Error() string {
	return fmt.Sprintf("[DELETE /api/functions/namespaces/{namespace}/tree/{workflow}?op=delete-service][%d] deleteWorkflowServiceOK ", 200)
}

func (o *DeleteWorkflowServiceOK) String() string {
	return fmt.Sprintf("[DELETE /api/functions/namespaces/{namespace}/tree/{workflow}?op=delete-service][%d] deleteWorkflowServiceOK ", 200)
}

func (o *DeleteWorkflowServiceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
