apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "direktiv.fullname" . }}-config-frontend
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
data:
  default.conf.template: |
      lua_shared_dict discovery 1m;
      lua_shared_dict jwks 1m;
      
      server {

        set $session_storage cookie;
        set $session_cookie_persistent on;
        set $session_cookie_secure on;
        set $session_cookie_httponly on;
        set $session_cookie_samesite Strict;

        server_tokens off;  

        listen 2304;
        
        resolver {{ .Values.frontend.nginx.resolver }}

        lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
        lua_ssl_verify_depth 5;

        root /usr/share/nginx/html;

        location /assets {
        }

        location /locales {
        }

        location = /favicon.ico {
        }

        location / {
          try_files $uri /index.html;
          {{ .Values.frontend.nginx.config | nindent 10 }}
        }

      }