apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "direktiv.fullname" . }}-flow
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.flow.replicas }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "direktiv.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "direktiv.selectorLabels" . | nindent 8 }}
        app: {{ include "direktiv.fullname" . }}-flow
    spec:
      {{- if gt (default $.Values.flow.replicas 1) 1 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                  - direktiv
            topologyKey: "kubernetes.io/hostname"
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "direktiv.serviceAccountName" . }}-functions
      containers:
{{- if .Values.opentelemetry.enabled }}
{{ include "direktiv.opentelemetry" . | indent 8 }}
{{- end }}
{{- if .Values.flow.extraContainers }}
{{ toYaml .Values.flow.extraContainers | indent 8}}
{{- end }}
        - name: flow
          securityContext:
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "4048Mi"
          image: "{{ .Values.registry }}/{{ .Values.image }}:{{ .Values.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: ["/bin/direktiv", "server"]
          volumeMounts:
          {{- if .Values.flow.extraVolumeMounts -}}
          {{ toYaml .Values.flow.extraVolumeMounts | nindent 10 }}
          {{- end }}
          ports:
            - name: flow-api
              containerPort: 6665
              protocol: TCP
          env:
          - name: DIREKTIV_DEBUG
            value: {{ .Values.flow.debug | quote }}
          - name: DIREKTIV_API_PORT
            value: "6665"
          {{- if ne .Values.apikey "none" }}
          - name: DIREKTIV_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "direktiv.fullname" . }}
                key: apikey
          {{- end }}
          {{- range .Values.flow.additionalSecEnvs }}
          - name: {{ .name | quote }}
            valueFrom:
               secretKeyRef:
                 name: {{ .secret | quote }}
                 key: {{ .key | quote }}
          {{- end }}
          {{- range .Values.flow.additionalEnvs }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
          {{- end }}
          - name: DIREKTIV_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "direktiv.fullname" . }}
                key: key
          - name: DIREKTIV_DB
            valueFrom:
              secretKeyRef:
                name: {{ include "direktiv.fullname" . }}
                key: db
          - name: DIREKTIV_FUNCTIONS_TIMEOUT
            value: {{ .Values.requestTimeout | quote }}
          - name: DIREKTIV_OPEN_TELEMETRY_BACKEND
            value: {{ include "direktiv.opentelemetry-backend" . }}
          - name: DIREKTIV_KNATIVE_SERVICE_ACCOUNT
            value: "{{ include "direktiv.serviceAccountName" . }}-functions-pod"
          - name: DIREKTIV_KNATIVE_NAMESPACE
            value: {{ .Values.functions.namespace | quote }}
          - name: DIREKTIV_KNATIVE_INGRESS_CLASS
            value: {{ .Values.functions.ingressClass | quote }}
          - name: DIREKTIV_KNATIVE_SIDECAR
            value: "{{ .Values.registry }}/{{ .Values.image }}:{{ .Values.tag | default .Chart.AppVersion }}"
          - name: DIREKTIV_KNATIVE_MAX_SCALE
            value: {{ .Values.flow.max_scale | quote }}
          {{- if .Values.netShape }}
          - name: DIREKTIV_KNATIVE_NET_SHAPE
            value: {{ .Values.netShape | quote }}
          {{- end }}
          - name: DIREKTIV_SERVICE_NAMESPACE
            value: {{ .Values.functions.namespace }}
          {{- if or (ne .Values.http_proxy "") (ne .Values.https_proxy "") }}
          - name: "HTTP_PROXY"
            value: "{{ .Values.http_proxy }}"
          - name: "HTTPS_PROXY"
            value: "{{ .Values.https_proxy }}"
          - name: "NO_PROXY"
            value: "{{ .Values.no_proxy }}"
          - name: "DIREKTIV_KNATIVE_PROXY_HTTP"
            value: "{{ .Values.http_proxy }}"
          - name: "DIREKTIV_KNATIVE_PROXY_HTTPS"
            value: "{{ .Values.https_proxy }}"
          - name: "DIREKTIV_KNATIVE_PROXY_NO"
            value: "{{ .Values.no_proxy }}"
          {{- end }}
          - name: DIREKTIV_DEPLOYMENT_NAME
            value: "{{ include "direktiv.fullname" . }}"
          - name: DIREKTIV_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- range .Values.flow.extraVariables }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
          {{- end }}

          - name: DIREKTIV_KNATIVE_SIZE_MEMORY_SMALL
            value: "{{ .Values.functions.limits.memory.small }}"
          - name: DIREKTIV_KNATIVE_SIZE_CPU_SMALL
            value: "{{ .Values.functions.limits.cpu.small }}"
          - name: DIREKTIV_KNATIVE_SIZE_DISK_SMALL
            value: "{{ .Values.functions.limits.disk.small }}"
          - name: DIREKTIV_KNATIVE_SIZE_MEMORY_MEDIUM
            value: "{{ .Values.functions.limits.memory.medium }}"
          - name: DIREKTIV_KNATIVE_SIZE_CPU_MEDIUM
            value: "{{ .Values.functions.limits.cpu.medium }}"
          - name: DIREKTIV_KNATIVE_SIZE_DISK_MEDIUM
            value: "{{ .Values.functions.limits.disk.medium }}"
          - name: DIREKTIV_KNATIVE_SIZE_MEMORY_LARGE
            value: "{{ .Values.functions.limits.memory.large }}"
          - name: DIREKTIV_KNATIVE_SIZE_CPU_LARGE
            value: "{{ .Values.functions.limits.cpu.large }}"
          - name: DIREKTIV_KNATIVE_SIZE_DISK_LARGE
            value: "{{ .Values.functions.limits.disk.large }}"
          # NATS Configuration
          - name: DIREKTIV_NATS_INSTALLED
            value: "{{ .Values.nats.install }}"
          - name: DIREKTIV_NATS_HOST
            value: "direktiv-nats.{{ .Release.Namespace }}.svc.cluster.local"          
          - name: DIREKTIV_NATS_PORT
            value: "{{ .Values.nats.config.port }}"
          - name: DIREKTIV_NATS_TLS
            value: "{{ .Values.nats.config.tls.enabled }}"
          - name: DIREKTIV_NATS_USERNAME
            value: "{{ .Values.nats.config.routeURLs.user }}"
          - name: DIREKTIV_NATS_PASSWORD
            value: "{{ .Values.nats.config.routeURLs.password }}"

      volumes:
{{- if .Values.opentelemetry.enabled }}
{{ include "direktiv.opentelemetry.volume" . | indent 8 }}
{{- end }}
        {{- if .Values.flow.extraVolumes }}
        {{ toYaml .Values.flow.extraVolumes | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.flow.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
