kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ include "direktiv.serviceAccountName" . }}-flow-role
 labels:
   {{- include "direktiv.labels" . | nindent 4 }}
rules:

- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "log", "delete"]

- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["list", "watch", "get"]

- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "update", "delete", "create", "deletecollection"]

- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete", "deletecollection", "watch"]

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]

- apiGroups: ["serving.knative.dev"]
  resources: ["*"]
  verbs: ["*"]
