kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ include "direktiv.serviceAccountName" . }}-flow-role-bind
subjects:
- kind: ServiceAccount
  name: {{ include "direktiv.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
 kind: Role
 name: {{ include "direktiv.serviceAccountName" . }}-flow-role
 apiGroup: rbac.authorization.k8s.io
