name: dagger
on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:

jobs:
  dagger:
    name: Dagger
    runs-on: ubuntu-latest
    steps:
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          module: github.com/shykes/daggerverse/hello@v0.1.2
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          args: build-ui --source=.
