name: Generate GO SDK from swagger.json
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: mkdir sdk
      - uses: actions/checkout@v2
        with:
          path: sdk
          repository: vorteil/direktivsdk
      - run: |
          download_url=$(curl -s https://api.github.com/repos/go-swagger/go-swagger/releases/latest | \
          jq -r '.assets[] | select(.name | contains("'"$(uname | tr '[:upper:]' '[:lower:]')"'_amd64")) | .browser_download_url')
          curl -o /usr/local/bin/swagger -L'#' "$download_url"
          chmod +x /usr/local/bin/swagger
      - run: swagger version