name: Generate GO SDK from swagger.json
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: mkdir sdk
      - uses: actions/checkout@v2
        with:
          path: sdk
          repository: vorteil/direktivsdk
      - run: alias swagger="docker run --rm -it  --user $(id -u):$(id -g) -e GOPATH=$HOME/go:/go -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger"
      - run: swagger version