name: Generate GO SDK from swagger.json
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: vorteil/direktivsdk
      - run: ls