apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-functions
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5555
      name: grpc
      protocol: TCP
  selector:
    {{- include "direktiv.selectorLabelsFunctions" . | nindent 4 }}
