{{- if .Values.eventing.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-eventing
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 1644
      name: eventing
      protocol: TCP
  selector:
    {{- include "direktiv.selectorLabels" . | nindent 4 }}
{{- end }}
